// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: acr_routing_schema.proto

package engine

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoutingSchemaType int32

const (
	RoutingSchemaType_default    RoutingSchemaType = 0
	RoutingSchemaType_voice      RoutingSchemaType = 1
	RoutingSchemaType_chat       RoutingSchemaType = 2
	RoutingSchemaType_processing RoutingSchemaType = 3
	RoutingSchemaType_service    RoutingSchemaType = 4
)

// Enum value maps for RoutingSchemaType.
var (
	RoutingSchemaType_name = map[int32]string{
		0: "default",
		1: "voice",
		2: "chat",
		3: "processing",
		4: "service",
	}
	RoutingSchemaType_value = map[string]int32{
		"default":    0,
		"voice":      1,
		"chat":       2,
		"processing": 3,
		"service":    4,
	}
)

func (x RoutingSchemaType) Enum() *RoutingSchemaType {
	p := new(RoutingSchemaType)
	*p = x
	return p
}

func (x RoutingSchemaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoutingSchemaType) Descriptor() protoreflect.EnumDescriptor {
	return file_acr_routing_schema_proto_enumTypes[0].Descriptor()
}

func (RoutingSchemaType) Type() protoreflect.EnumType {
	return &file_acr_routing_schema_proto_enumTypes[0]
}

func (x RoutingSchemaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoutingSchemaType.Descriptor instead.
func (RoutingSchemaType) EnumDescriptor() ([]byte, []int) {
	return file_acr_routing_schema_proto_rawDescGZIP(), []int{0}
}

type SchemaTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaTag) Reset() {
	*x = SchemaTag{}
	mi := &file_acr_routing_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaTag) ProtoMessage() {}

func (x *SchemaTag) ProtoReflect() protoreflect.Message {
	mi := &file_acr_routing_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaTag.ProtoReflect.Descriptor instead.
func (*SchemaTag) Descriptor() ([]byte, []int) {
	return file_acr_routing_schema_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PatchRoutingSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          RoutingSchemaType      `protobuf:"varint,4,opt,name=type,proto3,enum=engine.RoutingSchemaType" json:"type,omitempty"`
	Schema        *structpb.Value        `protobuf:"bytes,5,opt,name=schema,proto3" json:"schema,omitempty"`
	Payload       *structpb.Value        `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Debug         bool                   `protobuf:"varint,7,opt,name=debug,proto3" json:"debug,omitempty"`
	Fields        []string               `protobuf:"bytes,8,rep,name=fields,proto3" json:"fields,omitempty"`
	Editor        bool                   `protobuf:"varint,9,opt,name=editor,proto3" json:"editor,omitempty"`
	Tags          []*SchemaTag           `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Note          string                 `protobuf:"bytes,11,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchRoutingSchemaRequest) Reset() {
	*x = PatchRoutingSchemaRequest{}
	mi := &file_acr_routing_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchRoutingSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchRoutingSchemaRequest) ProtoMessage() {}

func (x *PatchRoutingSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acr_routing_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchRoutingSchemaRequest.ProtoReflect.Descriptor instead.
func (*PatchRoutingSchemaRequest) Descriptor() ([]byte, []int) {
	return file_acr_routing_schema_proto_rawDescGZIP(), []int{1}
}

func (x *PatchRoutingSchemaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchRoutingSchemaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatchRoutingSchemaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PatchRoutingSchemaRequest) GetType() RoutingSchemaType {
	if x != nil {
		return x.Type
	}
	return RoutingSchemaType_default
}

func (x *PatchRoutingSchemaRequest) GetSchema() *structpb.Value {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *PatchRoutingSchemaRequest) GetPayload() *structpb.Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PatchRoutingSchemaRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *PatchRoutingSchemaRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *PatchRoutingSchemaRequest) GetEditor() bool {
	if x != nil {
		return x.Editor
	}
	return false
}

func (x *PatchRoutingSchemaRequest) GetTags() []*SchemaTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PatchRoutingSchemaRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type DeleteRoutingSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId      int64                  `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoutingSchemaRequest) Reset() {
	*x = DeleteRoutingSchemaRequest{}
	mi := &file_acr_routing_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoutingSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoutingSchemaRequest) ProtoMessage() {}

func (x *DeleteRoutingSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acr_routing_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoutingSchemaRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoutingSchemaRequest) Descriptor() ([]byte, []int) {
	return file_acr_routing_schema_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRoutingSchemaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteRoutingSchemaRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

type UpdateRoutingSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          RoutingSchemaType      `protobuf:"varint,4,opt,name=type,proto3,enum=engine.RoutingSchemaType" json:"type,omitempty"`
	Schema        *structpb.Value        `protobuf:"bytes,5,opt,name=schema,proto3" json:"schema,omitempty"`
	Payload       *structpb.Value        `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Debug         bool                   `protobuf:"varint,7,opt,name=debug,proto3" json:"debug,omitempty"`
	Editor        bool                   `protobuf:"varint,8,opt,name=editor,proto3" json:"editor,omitempty"`
	Tags          []*SchemaTag           `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Note          string                 `protobuf:"bytes,10,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoutingSchemaRequest) Reset() {
	*x = UpdateRoutingSchemaRequest{}
	mi := &file_acr_routing_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoutingSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoutingSchemaRequest) ProtoMessage() {}

func (x *UpdateRoutingSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acr_routing_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoutingSchemaRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoutingSchemaRequest) Descriptor() ([]byte, []int) {
	return file_acr_routing_schema_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRoutingSchemaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoutingSchemaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoutingSchemaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRoutingSchemaRequest) GetType() RoutingSchemaType {
	if x != nil {
		return x.Type
	}
	return RoutingSchemaType_default
}

func (x *UpdateRoutingSchemaRequest) GetSchema() *structpb.Value {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *UpdateRoutingSchemaRequest) GetPayload() *structpb.Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateRoutingSchemaRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *UpdateRoutingSchemaRequest) GetEditor() bool {
	if x != nil {
		return x.Editor
	}
	return false
}

func (x *UpdateRoutingSchemaRequest) GetTags() []*SchemaTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateRoutingSchemaRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ReadRoutingSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId      int64                  `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRoutingSchemaRequest) Reset() {
	*x = ReadRoutingSchemaRequest{}
	mi := &file_acr_routing_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRoutingSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRoutingSchemaRequest) ProtoMessage() {}

func (x *ReadRoutingSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acr_routing_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRoutingSchemaRequest.ProtoReflect.Descriptor instead.
func (*ReadRoutingSchemaRequest) Descriptor() ([]byte, []int) {
	return file_acr_routing_schema_proto_rawDescGZIP(), []int{4}
}

func (x *ReadRoutingSchemaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReadRoutingSchemaRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

type SearchRoutingSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Q             string                 `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Fields        []string               `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	Id            []uint32               `protobuf:"varint,6,rep,packed,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Type          []RoutingSchemaType    `protobuf:"varint,8,rep,packed,name=type,proto3,enum=engine.RoutingSchemaType" json:"type,omitempty"`
	Editor        bool                   `protobuf:"varint,9,opt,name=editor,proto3" json:"editor,omitempty"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRoutingSchemaRequest) Reset() {
	*x = SearchRoutingSchemaRequest{}
	mi := &file_acr_routing_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRoutingSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRoutingSchemaRequest) ProtoMessage() {}

func (x *SearchRoutingSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acr_routing_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRoutingSchemaRequest.ProtoReflect.Descriptor instead.
func (*SearchRoutingSchemaRequest) Descriptor() ([]byte, []int) {
	return file_acr_routing_schema_proto_rawDescGZIP(), []int{5}
}

func (x *SearchRoutingSchemaRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRoutingSchemaRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchRoutingSchemaRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchRoutingSchemaRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchRoutingSchemaRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SearchRoutingSchemaRequest) GetId() []uint32 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SearchRoutingSchemaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchRoutingSchemaRequest) GetType() []RoutingSchemaType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *SearchRoutingSchemaRequest) GetEditor() bool {
	if x != nil {
		return x.Editor
	}
	return false
}

func (x *SearchRoutingSchemaRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateRoutingSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type          RoutingSchemaType      `protobuf:"varint,3,opt,name=type,proto3,enum=engine.RoutingSchemaType" json:"type,omitempty"`
	Schema        *structpb.Value        `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	Payload       *structpb.Value        `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Debug         bool                   `protobuf:"varint,6,opt,name=debug,proto3" json:"debug,omitempty"`
	Editor        bool                   `protobuf:"varint,7,opt,name=editor,proto3" json:"editor,omitempty"`
	Tags          []*SchemaTag           `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoutingSchemaRequest) Reset() {
	*x = CreateRoutingSchemaRequest{}
	mi := &file_acr_routing_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoutingSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoutingSchemaRequest) ProtoMessage() {}

func (x *CreateRoutingSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acr_routing_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoutingSchemaRequest.ProtoReflect.Descriptor instead.
func (*CreateRoutingSchemaRequest) Descriptor() ([]byte, []int) {
	return file_acr_routing_schema_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoutingSchemaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoutingSchemaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRoutingSchemaRequest) GetType() RoutingSchemaType {
	if x != nil {
		return x.Type
	}
	return RoutingSchemaType_default
}

func (x *CreateRoutingSchemaRequest) GetSchema() *structpb.Value {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *CreateRoutingSchemaRequest) GetPayload() *structpb.Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateRoutingSchemaRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *CreateRoutingSchemaRequest) GetEditor() bool {
	if x != nil {
		return x.Editor
	}
	return false
}

func (x *CreateRoutingSchemaRequest) GetTags() []*SchemaTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RoutingSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     *Lookup                `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     *Lookup                `protobuf:"bytes,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Type          RoutingSchemaType      `protobuf:"varint,8,opt,name=type,proto3,enum=engine.RoutingSchemaType" json:"type,omitempty"`
	Schema        *structpb.Value        `protobuf:"bytes,9,opt,name=schema,proto3" json:"schema,omitempty"`
	Payload       *structpb.Value        `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	Debug         bool                   `protobuf:"varint,11,opt,name=debug,proto3" json:"debug,omitempty"`
	Editor        bool                   `protobuf:"varint,12,opt,name=editor,proto3" json:"editor,omitempty"`
	Tags          []*SchemaTag           `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingSchema) Reset() {
	*x = RoutingSchema{}
	mi := &file_acr_routing_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingSchema) ProtoMessage() {}

func (x *RoutingSchema) ProtoReflect() protoreflect.Message {
	mi := &file_acr_routing_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingSchema.ProtoReflect.Descriptor instead.
func (*RoutingSchema) Descriptor() ([]byte, []int) {
	return file_acr_routing_schema_proto_rawDescGZIP(), []int{7}
}

func (x *RoutingSchema) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoutingSchema) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RoutingSchema) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *RoutingSchema) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *RoutingSchema) GetUpdatedBy() *Lookup {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

func (x *RoutingSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoutingSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoutingSchema) GetType() RoutingSchemaType {
	if x != nil {
		return x.Type
	}
	return RoutingSchemaType_default
}

func (x *RoutingSchema) GetSchema() *structpb.Value {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *RoutingSchema) GetPayload() *structpb.Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RoutingSchema) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *RoutingSchema) GetEditor() bool {
	if x != nil {
		return x.Editor
	}
	return false
}

func (x *RoutingSchema) GetTags() []*SchemaTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListRoutingSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Next          bool                   `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*RoutingSchema       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutingSchema) Reset() {
	*x = ListRoutingSchema{}
	mi := &file_acr_routing_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutingSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutingSchema) ProtoMessage() {}

func (x *ListRoutingSchema) ProtoReflect() protoreflect.Message {
	mi := &file_acr_routing_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutingSchema.ProtoReflect.Descriptor instead.
func (*ListRoutingSchema) Descriptor() ([]byte, []int) {
	return file_acr_routing_schema_proto_rawDescGZIP(), []int{8}
}

func (x *ListRoutingSchema) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *ListRoutingSchema) GetItems() []*RoutingSchema {
	if x != nil {
		return x.Items
	}
	return nil
}

type RoutingSchemaTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingSchemaTag) Reset() {
	*x = RoutingSchemaTag{}
	mi := &file_acr_routing_schema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingSchemaTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingSchemaTag) ProtoMessage() {}

func (x *RoutingSchemaTag) ProtoReflect() protoreflect.Message {
	mi := &file_acr_routing_schema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingSchemaTag.ProtoReflect.Descriptor instead.
func (*RoutingSchemaTag) Descriptor() ([]byte, []int) {
	return file_acr_routing_schema_proto_rawDescGZIP(), []int{9}
}

func (x *RoutingSchemaTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoutingSchemaTag) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListRoutingSchemaTags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Next          bool                   `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*RoutingSchemaTag    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutingSchemaTags) Reset() {
	*x = ListRoutingSchemaTags{}
	mi := &file_acr_routing_schema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutingSchemaTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutingSchemaTags) ProtoMessage() {}

func (x *ListRoutingSchemaTags) ProtoReflect() protoreflect.Message {
	mi := &file_acr_routing_schema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutingSchemaTags.ProtoReflect.Descriptor instead.
func (*ListRoutingSchemaTags) Descriptor() ([]byte, []int) {
	return file_acr_routing_schema_proto_rawDescGZIP(), []int{10}
}

func (x *ListRoutingSchemaTags) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *ListRoutingSchemaTags) GetItems() []*RoutingSchemaTag {
	if x != nil {
		return x.Items
	}
	return nil
}

type SearchRoutingSchemaTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Q             string                 `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Fields        []string               `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	Type          []RoutingSchemaType    `protobuf:"varint,6,rep,packed,name=type,proto3,enum=engine.RoutingSchemaType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRoutingSchemaTagsRequest) Reset() {
	*x = SearchRoutingSchemaTagsRequest{}
	mi := &file_acr_routing_schema_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRoutingSchemaTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRoutingSchemaTagsRequest) ProtoMessage() {}

func (x *SearchRoutingSchemaTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acr_routing_schema_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRoutingSchemaTagsRequest.ProtoReflect.Descriptor instead.
func (*SearchRoutingSchemaTagsRequest) Descriptor() ([]byte, []int) {
	return file_acr_routing_schema_proto_rawDescGZIP(), []int{11}
}

func (x *SearchRoutingSchemaTagsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRoutingSchemaTagsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchRoutingSchemaTagsRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchRoutingSchemaTagsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchRoutingSchemaTagsRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SearchRoutingSchemaTagsRequest) GetType() []RoutingSchemaType {
	if x != nil {
		return x.Type
	}
	return nil
}

var File_acr_routing_schema_proto protoreflect.FileDescriptor

const file_acr_routing_schema_proto_rawDesc = "" +
	"\n" +
	"\x18acr_routing_schema.proto\x12\x06engine\x1a\vconst.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1cgoogle/api/annotations.proto\"\x1f\n" +
	"\tSchemaTag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xf3\x02\n" +
	"\x19PatchRoutingSchemaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12-\n" +
	"\x04type\x18\x04 \x01(\x0e2\x19.engine.RoutingSchemaTypeR\x04type\x12.\n" +
	"\x06schema\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\x06schema\x120\n" +
	"\apayload\x18\x06 \x01(\v2\x16.google.protobuf.ValueR\apayload\x12\x14\n" +
	"\x05debug\x18\a \x01(\bR\x05debug\x12\x16\n" +
	"\x06fields\x18\b \x03(\tR\x06fields\x12\x16\n" +
	"\x06editor\x18\t \x01(\bR\x06editor\x12%\n" +
	"\x04tags\x18\n" +
	" \x03(\v2\x11.engine.SchemaTagR\x04tags\x12\x12\n" +
	"\x04note\x18\v \x01(\tR\x04note\"I\n" +
	"\x1aDeleteRoutingSchemaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x03R\bdomainId\"\xdc\x02\n" +
	"\x1aUpdateRoutingSchemaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12-\n" +
	"\x04type\x18\x04 \x01(\x0e2\x19.engine.RoutingSchemaTypeR\x04type\x12.\n" +
	"\x06schema\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\x06schema\x120\n" +
	"\apayload\x18\x06 \x01(\v2\x16.google.protobuf.ValueR\apayload\x12\x14\n" +
	"\x05debug\x18\a \x01(\bR\x05debug\x12\x16\n" +
	"\x06editor\x18\b \x01(\bR\x06editor\x12%\n" +
	"\x04tags\x18\t \x03(\v2\x11.engine.SchemaTagR\x04tags\x12\x12\n" +
	"\x04note\x18\n" +
	" \x01(\tR\x04note\"G\n" +
	"\x18ReadRoutingSchemaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x03R\bdomainId\"\xfd\x01\n" +
	"\x1aSearchRoutingSchemaRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\f\n" +
	"\x01q\x18\x03 \x01(\tR\x01q\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x16\n" +
	"\x06fields\x18\x05 \x03(\tR\x06fields\x12\x0e\n" +
	"\x02id\x18\x06 \x03(\rR\x02id\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12-\n" +
	"\x04type\x18\b \x03(\x0e2\x19.engine.RoutingSchemaTypeR\x04type\x12\x16\n" +
	"\x06editor\x18\t \x01(\bR\x06editor\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\"\xb8\x02\n" +
	"\x1aCreateRoutingSchemaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.engine.RoutingSchemaTypeR\x04type\x12.\n" +
	"\x06schema\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\x06schema\x120\n" +
	"\apayload\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\apayload\x12\x14\n" +
	"\x05debug\x18\x06 \x01(\bR\x05debug\x12\x16\n" +
	"\x06editor\x18\a \x01(\bR\x06editor\x12%\n" +
	"\x04tags\x18\b \x03(\v2\x11.engine.SchemaTagR\x04tags\"\xd7\x03\n" +
	"\rRoutingSchema\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12-\n" +
	"\n" +
	"created_by\x18\x03 \x01(\v2\x0e.engine.LookupR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\x12-\n" +
	"\n" +
	"updated_by\x18\x05 \x01(\v2\x0e.engine.LookupR\tupdatedBy\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12-\n" +
	"\x04type\x18\b \x01(\x0e2\x19.engine.RoutingSchemaTypeR\x04type\x12.\n" +
	"\x06schema\x18\t \x01(\v2\x16.google.protobuf.ValueR\x06schema\x120\n" +
	"\apayload\x18\n" +
	" \x01(\v2\x16.google.protobuf.ValueR\apayload\x12\x14\n" +
	"\x05debug\x18\v \x01(\bR\x05debug\x12\x16\n" +
	"\x06editor\x18\f \x01(\bR\x06editor\x12%\n" +
	"\x04tags\x18\r \x03(\v2\x11.engine.SchemaTagR\x04tags\"T\n" +
	"\x11ListRoutingSchema\x12\x12\n" +
	"\x04next\x18\x01 \x01(\bR\x04next\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.engine.RoutingSchemaR\x05items\"<\n" +
	"\x10RoutingSchemaTag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"[\n" +
	"\x15ListRoutingSchemaTags\x12\x12\n" +
	"\x04next\x18\x01 \x01(\bR\x04next\x12.\n" +
	"\x05items\x18\x02 \x03(\v2\x18.engine.RoutingSchemaTagR\x05items\"\xb1\x01\n" +
	"\x1eSearchRoutingSchemaTagsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\f\n" +
	"\x01q\x18\x03 \x01(\tR\x01q\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x16\n" +
	"\x06fields\x18\x05 \x03(\tR\x06fields\x12-\n" +
	"\x04type\x18\x06 \x03(\x0e2\x19.engine.RoutingSchemaTypeR\x04type*R\n" +
	"\x11RoutingSchemaType\x12\v\n" +
	"\adefault\x10\x00\x12\t\n" +
	"\x05voice\x10\x01\x12\b\n" +
	"\x04chat\x10\x02\x12\x0e\n" +
	"\n" +
	"processing\x10\x03\x12\v\n" +
	"\aservice\x10\x042\xb3\x06\n" +
	"\x14RoutingSchemaService\x12l\n" +
	"\x13CreateRoutingSchema\x12\".engine.CreateRoutingSchemaRequest\x1a\x15.engine.RoutingSchema\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/routing/schema\x12m\n" +
	"\x13SearchRoutingSchema\x12\".engine.SearchRoutingSchemaRequest\x1a\x19.engine.ListRoutingSchema\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/routing/schema\x12j\n" +
	"\x11ReadRoutingSchema\x12 .engine.ReadRoutingSchemaRequest\x1a\x15.engine.RoutingSchema\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/routing/schema/{id}\x12q\n" +
	"\x13UpdateRoutingSchema\x12\".engine.UpdateRoutingSchemaRequest\x1a\x15.engine.RoutingSchema\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/routing/schema/{id}\x12o\n" +
	"\x12PatchRoutingSchema\x12!.engine.PatchRoutingSchemaRequest\x1a\x15.engine.RoutingSchema\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*2\x14/routing/schema/{id}\x12n\n" +
	"\x13DeleteRoutingSchema\x12\".engine.DeleteRoutingSchemaRequest\x1a\x15.engine.RoutingSchema\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/routing/schema/{id}\x12~\n" +
	"\x17SearchRoutingSchemaTags\x12&.engine.SearchRoutingSchemaTagsRequest\x1a\x1d.engine.ListRoutingSchemaTags\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/routing/schema/tagsB\"Z github.com/webitel/protos/engineb\x06proto3"

var (
	file_acr_routing_schema_proto_rawDescOnce sync.Once
	file_acr_routing_schema_proto_rawDescData []byte
)

func file_acr_routing_schema_proto_rawDescGZIP() []byte {
	file_acr_routing_schema_proto_rawDescOnce.Do(func() {
		file_acr_routing_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acr_routing_schema_proto_rawDesc), len(file_acr_routing_schema_proto_rawDesc)))
	})
	return file_acr_routing_schema_proto_rawDescData
}

var file_acr_routing_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_acr_routing_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_acr_routing_schema_proto_goTypes = []any{
	(RoutingSchemaType)(0),                 // 0: engine.RoutingSchemaType
	(*SchemaTag)(nil),                      // 1: engine.SchemaTag
	(*PatchRoutingSchemaRequest)(nil),      // 2: engine.PatchRoutingSchemaRequest
	(*DeleteRoutingSchemaRequest)(nil),     // 3: engine.DeleteRoutingSchemaRequest
	(*UpdateRoutingSchemaRequest)(nil),     // 4: engine.UpdateRoutingSchemaRequest
	(*ReadRoutingSchemaRequest)(nil),       // 5: engine.ReadRoutingSchemaRequest
	(*SearchRoutingSchemaRequest)(nil),     // 6: engine.SearchRoutingSchemaRequest
	(*CreateRoutingSchemaRequest)(nil),     // 7: engine.CreateRoutingSchemaRequest
	(*RoutingSchema)(nil),                  // 8: engine.RoutingSchema
	(*ListRoutingSchema)(nil),              // 9: engine.ListRoutingSchema
	(*RoutingSchemaTag)(nil),               // 10: engine.RoutingSchemaTag
	(*ListRoutingSchemaTags)(nil),          // 11: engine.ListRoutingSchemaTags
	(*SearchRoutingSchemaTagsRequest)(nil), // 12: engine.SearchRoutingSchemaTagsRequest
	(*structpb.Value)(nil),                 // 13: google.protobuf.Value
	(*Lookup)(nil),                         // 14: engine.Lookup
}
var file_acr_routing_schema_proto_depIdxs = []int32{
	0,  // 0: engine.PatchRoutingSchemaRequest.type:type_name -> engine.RoutingSchemaType
	13, // 1: engine.PatchRoutingSchemaRequest.schema:type_name -> google.protobuf.Value
	13, // 2: engine.PatchRoutingSchemaRequest.payload:type_name -> google.protobuf.Value
	1,  // 3: engine.PatchRoutingSchemaRequest.tags:type_name -> engine.SchemaTag
	0,  // 4: engine.UpdateRoutingSchemaRequest.type:type_name -> engine.RoutingSchemaType
	13, // 5: engine.UpdateRoutingSchemaRequest.schema:type_name -> google.protobuf.Value
	13, // 6: engine.UpdateRoutingSchemaRequest.payload:type_name -> google.protobuf.Value
	1,  // 7: engine.UpdateRoutingSchemaRequest.tags:type_name -> engine.SchemaTag
	0,  // 8: engine.SearchRoutingSchemaRequest.type:type_name -> engine.RoutingSchemaType
	0,  // 9: engine.CreateRoutingSchemaRequest.type:type_name -> engine.RoutingSchemaType
	13, // 10: engine.CreateRoutingSchemaRequest.schema:type_name -> google.protobuf.Value
	13, // 11: engine.CreateRoutingSchemaRequest.payload:type_name -> google.protobuf.Value
	1,  // 12: engine.CreateRoutingSchemaRequest.tags:type_name -> engine.SchemaTag
	14, // 13: engine.RoutingSchema.created_by:type_name -> engine.Lookup
	14, // 14: engine.RoutingSchema.updated_by:type_name -> engine.Lookup
	0,  // 15: engine.RoutingSchema.type:type_name -> engine.RoutingSchemaType
	13, // 16: engine.RoutingSchema.schema:type_name -> google.protobuf.Value
	13, // 17: engine.RoutingSchema.payload:type_name -> google.protobuf.Value
	1,  // 18: engine.RoutingSchema.tags:type_name -> engine.SchemaTag
	8,  // 19: engine.ListRoutingSchema.items:type_name -> engine.RoutingSchema
	10, // 20: engine.ListRoutingSchemaTags.items:type_name -> engine.RoutingSchemaTag
	0,  // 21: engine.SearchRoutingSchemaTagsRequest.type:type_name -> engine.RoutingSchemaType
	7,  // 22: engine.RoutingSchemaService.CreateRoutingSchema:input_type -> engine.CreateRoutingSchemaRequest
	6,  // 23: engine.RoutingSchemaService.SearchRoutingSchema:input_type -> engine.SearchRoutingSchemaRequest
	5,  // 24: engine.RoutingSchemaService.ReadRoutingSchema:input_type -> engine.ReadRoutingSchemaRequest
	4,  // 25: engine.RoutingSchemaService.UpdateRoutingSchema:input_type -> engine.UpdateRoutingSchemaRequest
	2,  // 26: engine.RoutingSchemaService.PatchRoutingSchema:input_type -> engine.PatchRoutingSchemaRequest
	3,  // 27: engine.RoutingSchemaService.DeleteRoutingSchema:input_type -> engine.DeleteRoutingSchemaRequest
	12, // 28: engine.RoutingSchemaService.SearchRoutingSchemaTags:input_type -> engine.SearchRoutingSchemaTagsRequest
	8,  // 29: engine.RoutingSchemaService.CreateRoutingSchema:output_type -> engine.RoutingSchema
	9,  // 30: engine.RoutingSchemaService.SearchRoutingSchema:output_type -> engine.ListRoutingSchema
	8,  // 31: engine.RoutingSchemaService.ReadRoutingSchema:output_type -> engine.RoutingSchema
	8,  // 32: engine.RoutingSchemaService.UpdateRoutingSchema:output_type -> engine.RoutingSchema
	8,  // 33: engine.RoutingSchemaService.PatchRoutingSchema:output_type -> engine.RoutingSchema
	8,  // 34: engine.RoutingSchemaService.DeleteRoutingSchema:output_type -> engine.RoutingSchema
	11, // 35: engine.RoutingSchemaService.SearchRoutingSchemaTags:output_type -> engine.ListRoutingSchemaTags
	29, // [29:36] is the sub-list for method output_type
	22, // [22:29] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_acr_routing_schema_proto_init() }
func file_acr_routing_schema_proto_init() {
	if File_acr_routing_schema_proto != nil {
		return
	}
	file_const_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acr_routing_schema_proto_rawDesc), len(file_acr_routing_schema_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_acr_routing_schema_proto_goTypes,
		DependencyIndexes: file_acr_routing_schema_proto_depIdxs,
		EnumInfos:         file_acr_routing_schema_proto_enumTypes,
		MessageInfos:      file_acr_routing_schema_proto_msgTypes,
	}.Build()
	File_acr_routing_schema_proto = out.File
	file_acr_routing_schema_proto_goTypes = nil
	file_acr_routing_schema_proto_depIdxs = nil
}
