// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: skill.proto

package engine

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteSkillAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       int64                  `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Id            []int64                `protobuf:"varint,2,rep,packed,name=id,proto3" json:"id,omitempty"`
	AgentId       []int64                `protobuf:"varint,3,rep,packed,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkillAgentRequest) Reset() {
	*x = DeleteSkillAgentRequest{}
	mi := &file_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkillAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillAgentRequest) ProtoMessage() {}

func (x *DeleteSkillAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteSkillAgentRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteSkillAgentRequest) GetSkillId() int64 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *DeleteSkillAgentRequest) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *DeleteSkillAgentRequest) GetAgentId() []int64 {
	if x != nil {
		return x.AgentId
	}
	return nil
}

type DeleteSkillAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SkillAgentItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkillAgentResponse) Reset() {
	*x = DeleteSkillAgentResponse{}
	mi := &file_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkillAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillAgentResponse) ProtoMessage() {}

func (x *DeleteSkillAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillAgentResponse.ProtoReflect.Descriptor instead.
func (*DeleteSkillAgentResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteSkillAgentResponse) GetItems() []*SkillAgentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PatchSkillAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       int64                  `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Fields        []string               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Skill         *Lookup                `protobuf:"bytes,3,opt,name=skill,proto3" json:"skill,omitempty"`
	Capacity      *wrapperspb.Int32Value `protobuf:"bytes,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Id            []int64                `protobuf:"varint,6,rep,packed,name=id,proto3" json:"id,omitempty"`
	AgentId       []int64                `protobuf:"varint,7,rep,packed,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchSkillAgentRequest) Reset() {
	*x = PatchSkillAgentRequest{}
	mi := &file_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchSkillAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchSkillAgentRequest) ProtoMessage() {}

func (x *PatchSkillAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchSkillAgentRequest.ProtoReflect.Descriptor instead.
func (*PatchSkillAgentRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{2}
}

func (x *PatchSkillAgentRequest) GetSkillId() int64 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *PatchSkillAgentRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *PatchSkillAgentRequest) GetSkill() *Lookup {
	if x != nil {
		return x.Skill
	}
	return nil
}

func (x *PatchSkillAgentRequest) GetCapacity() *wrapperspb.Int32Value {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *PatchSkillAgentRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PatchSkillAgentRequest) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PatchSkillAgentRequest) GetAgentId() []int64 {
	if x != nil {
		return x.AgentId
	}
	return nil
}

type CreateSkillAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SkillAgentItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillAgentResponse) Reset() {
	*x = CreateSkillAgentResponse{}
	mi := &file_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillAgentResponse) ProtoMessage() {}

func (x *CreateSkillAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillAgentResponse.ProtoReflect.Descriptor instead.
func (*CreateSkillAgentResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSkillAgentResponse) GetItems() []*SkillAgentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PatchSkillAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SkillAgentItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchSkillAgentResponse) Reset() {
	*x = PatchSkillAgentResponse{}
	mi := &file_skill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchSkillAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchSkillAgentResponse) ProtoMessage() {}

func (x *PatchSkillAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchSkillAgentResponse.ProtoReflect.Descriptor instead.
func (*PatchSkillAgentResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{4}
}

func (x *PatchSkillAgentResponse) GetItems() []*SkillAgentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateSkillAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       int64                  `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Agent         []*Lookup              `protobuf:"bytes,2,rep,name=agent,proto3" json:"agent,omitempty"`
	Capacity      *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillAgentRequest) Reset() {
	*x = CreateSkillAgentRequest{}
	mi := &file_skill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillAgentRequest) ProtoMessage() {}

func (x *CreateSkillAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateSkillAgentRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSkillAgentRequest) GetSkillId() int64 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *CreateSkillAgentRequest) GetAgent() []*Lookup {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *CreateSkillAgentRequest) GetCapacity() *wrapperspb.Int32Value {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *CreateSkillAgentRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SkillAgentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Skill         *Lookup                `protobuf:"bytes,2,opt,name=skill,proto3" json:"skill,omitempty"`
	Capacity      *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Agent         *Lookup                `protobuf:"bytes,5,opt,name=agent,proto3" json:"agent,omitempty"`
	Team          *Lookup                `protobuf:"bytes,6,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillAgentItem) Reset() {
	*x = SkillAgentItem{}
	mi := &file_skill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillAgentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillAgentItem) ProtoMessage() {}

func (x *SkillAgentItem) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillAgentItem.ProtoReflect.Descriptor instead.
func (*SkillAgentItem) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{6}
}

func (x *SkillAgentItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SkillAgentItem) GetSkill() *Lookup {
	if x != nil {
		return x.Skill
	}
	return nil
}

func (x *SkillAgentItem) GetCapacity() *wrapperspb.Int32Value {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *SkillAgentItem) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SkillAgentItem) GetAgent() *Lookup {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *SkillAgentItem) GetTeam() *Lookup {
	if x != nil {
		return x.Team
	}
	return nil
}

type SearchSkillAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       int64                  `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Q             string                 `protobuf:"bytes,4,opt,name=q,proto3" json:"q,omitempty"`
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Fields        []string               `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	Id            []int64                `protobuf:"varint,7,rep,packed,name=id,proto3" json:"id,omitempty"`
	AgentId       []int64                `protobuf:"varint,8,rep,packed,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSkillAgentRequest) Reset() {
	*x = SearchSkillAgentRequest{}
	mi := &file_skill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSkillAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSkillAgentRequest) ProtoMessage() {}

func (x *SearchSkillAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSkillAgentRequest.ProtoReflect.Descriptor instead.
func (*SearchSkillAgentRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{7}
}

func (x *SearchSkillAgentRequest) GetSkillId() int64 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *SearchSkillAgentRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchSkillAgentRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchSkillAgentRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchSkillAgentRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchSkillAgentRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SearchSkillAgentRequest) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SearchSkillAgentRequest) GetAgentId() []int64 {
	if x != nil {
		return x.AgentId
	}
	return nil
}

type ListSkillAgent struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Next          bool                         `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*SkillAgentItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Aggs          *ListSkillAgent_ListSkillAgg `protobuf:"bytes,3,opt,name=aggs,proto3" json:"aggs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillAgent) Reset() {
	*x = ListSkillAgent{}
	mi := &file_skill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillAgent) ProtoMessage() {}

func (x *ListSkillAgent) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillAgent.ProtoReflect.Descriptor instead.
func (*ListSkillAgent) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{8}
}

func (x *ListSkillAgent) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *ListSkillAgent) GetItems() []*SkillAgentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListSkillAgent) GetAggs() *ListSkillAgent_ListSkillAgg {
	if x != nil {
		return x.Aggs
	}
	return nil
}

type ReadSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId      int64                  `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSkillRequest) Reset() {
	*x = ReadSkillRequest{}
	mi := &file_skill_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSkillRequest) ProtoMessage() {}

func (x *ReadSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSkillRequest.ProtoReflect.Descriptor instead.
func (*ReadSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{9}
}

func (x *ReadSkillRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReadSkillRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

type DeleteSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId      int64                  `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkillRequest) Reset() {
	*x = DeleteSkillRequest{}
	mi := &file_skill_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillRequest) ProtoMessage() {}

func (x *DeleteSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillRequest.ProtoReflect.Descriptor instead.
func (*DeleteSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSkillRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteSkillRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

type SearchSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Q             string                 `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Fields        []string               `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	Id            []uint32               `protobuf:"varint,6,rep,packed,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSkillRequest) Reset() {
	*x = SearchSkillRequest{}
	mi := &file_skill_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSkillRequest) ProtoMessage() {}

func (x *SearchSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSkillRequest.ProtoReflect.Descriptor instead.
func (*SearchSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{11}
}

func (x *SearchSkillRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchSkillRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchSkillRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchSkillRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchSkillRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SearchSkillRequest) GetId() []uint32 {
	if x != nil {
		return x.Id
	}
	return nil
}

type CreateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DomainId      int64                  `protobuf:"varint,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillRequest) Reset() {
	*x = CreateSkillRequest{}
	mi := &file_skill_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillRequest) ProtoMessage() {}

func (x *CreateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillRequest.ProtoReflect.Descriptor instead.
func (*CreateSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{12}
}

func (x *CreateSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSkillRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSkillRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

type UpdateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DomainId      int64                  `protobuf:"varint,4,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkillRequest) Reset() {
	*x = UpdateSkillRequest{}
	mi := &file_skill_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkillRequest) ProtoMessage() {}

func (x *UpdateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkillRequest.ProtoReflect.Descriptor instead.
func (*UpdateSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateSkillRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSkillRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSkillRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId      int64                  `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ActiveAgents  int32                  `protobuf:"varint,5,opt,name=active_agents,json=activeAgents,proto3" json:"active_agents,omitempty"`
	TotalAgents   int32                  `protobuf:"varint,6,opt,name=total_agents,json=totalAgents,proto3" json:"total_agents,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     *Lookup                `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     *Lookup                `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_skill_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{14}
}

func (x *Skill) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Skill) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skill) GetActiveAgents() int32 {
	if x != nil {
		return x.ActiveAgents
	}
	return 0
}

func (x *Skill) GetTotalAgents() int32 {
	if x != nil {
		return x.TotalAgents
	}
	return 0
}

func (x *Skill) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Skill) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Skill) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Skill) GetUpdatedBy() *Lookup {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

type ListSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Next          bool                   `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*Skill               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkill) Reset() {
	*x = ListSkill{}
	mi := &file_skill_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkill) ProtoMessage() {}

func (x *ListSkill) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkill.ProtoReflect.Descriptor instead.
func (*ListSkill) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{15}
}

func (x *ListSkill) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *ListSkill) GetItems() []*Skill {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListSkillAgent_ListSkillAgg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillAgent_ListSkillAgg) Reset() {
	*x = ListSkillAgent_ListSkillAgg{}
	mi := &file_skill_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillAgent_ListSkillAgg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillAgent_ListSkillAgg) ProtoMessage() {}

func (x *ListSkillAgent_ListSkillAgg) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillAgent_ListSkillAgg.ProtoReflect.Descriptor instead.
func (*ListSkillAgent_ListSkillAgg) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ListSkillAgent_ListSkillAgg) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_skill_proto protoreflect.FileDescriptor

const file_skill_proto_rawDesc = "" +
	"\n" +
	"\vskill.proto\x12\x06engine\x1a\vconst.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\"_\n" +
	"\x17DeleteSkillAgentRequest\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x03R\askillId\x12\x0e\n" +
	"\x02id\x18\x02 \x03(\x03R\x02id\x12\x19\n" +
	"\bagent_id\x18\x03 \x03(\x03R\aagentId\"H\n" +
	"\x18DeleteSkillAgentResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.engine.SkillAgentItemR\x05items\"\xef\x01\n" +
	"\x16PatchSkillAgentRequest\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x03R\askillId\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\x12$\n" +
	"\x05skill\x18\x03 \x01(\v2\x0e.engine.LookupR\x05skill\x127\n" +
	"\bcapacity\x18\x04 \x01(\v2\x1b.google.protobuf.Int32ValueR\bcapacity\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x0e\n" +
	"\x02id\x18\x06 \x03(\x03R\x02id\x12\x19\n" +
	"\bagent_id\x18\a \x03(\x03R\aagentId\"H\n" +
	"\x18CreateSkillAgentResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.engine.SkillAgentItemR\x05items\"G\n" +
	"\x17PatchSkillAgentResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.engine.SkillAgentItemR\x05items\"\xad\x01\n" +
	"\x17CreateSkillAgentRequest\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x03R\askillId\x12$\n" +
	"\x05agent\x18\x02 \x03(\v2\x0e.engine.LookupR\x05agent\x127\n" +
	"\bcapacity\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\bcapacity\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\"\xe3\x01\n" +
	"\x0eSkillAgentItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\x05skill\x18\x02 \x01(\v2\x0e.engine.LookupR\x05skill\x127\n" +
	"\bcapacity\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\bcapacity\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12$\n" +
	"\x05agent\x18\x05 \x01(\v2\x0e.engine.LookupR\x05agent\x12\"\n" +
	"\x04team\x18\x06 \x01(\v2\x0e.engine.LookupR\x04team\"\xc1\x01\n" +
	"\x17SearchSkillAgentRequest\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x03R\askillId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\f\n" +
	"\x01q\x18\x04 \x01(\tR\x01q\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\x12\x16\n" +
	"\x06fields\x18\x06 \x03(\tR\x06fields\x12\x0e\n" +
	"\x02id\x18\a \x03(\x03R\x02id\x12\x19\n" +
	"\bagent_id\x18\b \x03(\x03R\aagentId\"\xb5\x01\n" +
	"\x0eListSkillAgent\x12\x12\n" +
	"\x04next\x18\x01 \x01(\bR\x04next\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.engine.SkillAgentItemR\x05items\x127\n" +
	"\x04aggs\x18\x03 \x01(\v2#.engine.ListSkillAgent.ListSkillAggR\x04aggs\x1a(\n" +
	"\fListSkillAgg\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"?\n" +
	"\x10ReadSkillRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x03R\bdomainId\"A\n" +
	"\x12DeleteSkillRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x03R\bdomainId\"\x86\x01\n" +
	"\x12SearchSkillRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\f\n" +
	"\x01q\x18\x03 \x01(\tR\x01q\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x16\n" +
	"\x06fields\x18\x05 \x03(\tR\x06fields\x12\x0e\n" +
	"\x02id\x18\x06 \x03(\rR\x02id\"g\n" +
	"\x12CreateSkillRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdomain_id\x18\x03 \x01(\x03R\bdomainId\"w\n" +
	"\x12UpdateSkillRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdomain_id\x18\x04 \x01(\x03R\bdomainId\"\xce\x02\n" +
	"\x05Skill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x03R\bdomainId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\ractive_agents\x18\x05 \x01(\x05R\factiveAgents\x12!\n" +
	"\ftotal_agents\x18\x06 \x01(\x05R\vtotalAgents\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12-\n" +
	"\n" +
	"created_by\x18\b \x01(\v2\x0e.engine.LookupR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12-\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\v2\x0e.engine.LookupR\tupdatedBy\"D\n" +
	"\tListSkill\x12\x12\n" +
	"\x04next\x18\x01 \x01(\bR\x04next\x12#\n" +
	"\x05items\x18\x02 \x03(\v2\r.engine.SkillR\x05items2\xed\a\n" +
	"\fSkillService\x12X\n" +
	"\vCreateSkill\x12\x1a.engine.CreateSkillRequest\x1a\r.engine.Skill\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/call_center/skills\x12Y\n" +
	"\vSearchSkill\x12\x1a.engine.SearchSkillRequest\x1a\x11.engine.ListSkill\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/call_center/skills\x12V\n" +
	"\tReadSkill\x12\x18.engine.ReadSkillRequest\x1a\r.engine.Skill\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/call_center/skills/{id}\x12]\n" +
	"\vUpdateSkill\x12\x1a.engine.UpdateSkillRequest\x1a\r.engine.Skill\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/call_center/skills/{id}\x12Z\n" +
	"\vDeleteSkill\x12\x1a.engine.DeleteSkillRequest\x1a\r.engine.Skill\" \x82\xd3\xe4\x93\x02\x1a*\x18/call_center/skills/{id}\x12z\n" +
	"\x10SearchSkillAgent\x12\x1f.engine.SearchSkillAgentRequest\x1a\x16.engine.ListSkillAgent\"-\x82\xd3\xe4\x93\x02'\x12%/call_center/skills/{skill_id}/agents\x12\x87\x01\n" +
	"\x10CreateSkillAgent\x12\x1f.engine.CreateSkillAgentRequest\x1a .engine.CreateSkillAgentResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/call_center/skills/{skill_id}/agents\x12\x84\x01\n" +
	"\x0fPatchSkillAgent\x12\x1e.engine.PatchSkillAgentRequest\x1a\x1f.engine.PatchSkillAgentResponse\"0\x82\xd3\xe4\x93\x02*:\x01*2%/call_center/skills/{skill_id}/agents\x12\x87\x01\n" +
	"\x10DeleteSkillAgent\x12\x1f.engine.DeleteSkillAgentRequest\x1a .engine.DeleteSkillAgentResponse\"0\x82\xd3\xe4\x93\x02*:\x01**%/call_center/skills/{skill_id}/agentsB\"Z github.com/webitel/protos/engineb\x06proto3"

var (
	file_skill_proto_rawDescOnce sync.Once
	file_skill_proto_rawDescData []byte
)

func file_skill_proto_rawDescGZIP() []byte {
	file_skill_proto_rawDescOnce.Do(func() {
		file_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skill_proto_rawDesc), len(file_skill_proto_rawDesc)))
	})
	return file_skill_proto_rawDescData
}

var file_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_skill_proto_goTypes = []any{
	(*DeleteSkillAgentRequest)(nil),     // 0: engine.DeleteSkillAgentRequest
	(*DeleteSkillAgentResponse)(nil),    // 1: engine.DeleteSkillAgentResponse
	(*PatchSkillAgentRequest)(nil),      // 2: engine.PatchSkillAgentRequest
	(*CreateSkillAgentResponse)(nil),    // 3: engine.CreateSkillAgentResponse
	(*PatchSkillAgentResponse)(nil),     // 4: engine.PatchSkillAgentResponse
	(*CreateSkillAgentRequest)(nil),     // 5: engine.CreateSkillAgentRequest
	(*SkillAgentItem)(nil),              // 6: engine.SkillAgentItem
	(*SearchSkillAgentRequest)(nil),     // 7: engine.SearchSkillAgentRequest
	(*ListSkillAgent)(nil),              // 8: engine.ListSkillAgent
	(*ReadSkillRequest)(nil),            // 9: engine.ReadSkillRequest
	(*DeleteSkillRequest)(nil),          // 10: engine.DeleteSkillRequest
	(*SearchSkillRequest)(nil),          // 11: engine.SearchSkillRequest
	(*CreateSkillRequest)(nil),          // 12: engine.CreateSkillRequest
	(*UpdateSkillRequest)(nil),          // 13: engine.UpdateSkillRequest
	(*Skill)(nil),                       // 14: engine.Skill
	(*ListSkill)(nil),                   // 15: engine.ListSkill
	(*ListSkillAgent_ListSkillAgg)(nil), // 16: engine.ListSkillAgent.ListSkillAgg
	(*Lookup)(nil),                      // 17: engine.Lookup
	(*wrapperspb.Int32Value)(nil),       // 18: google.protobuf.Int32Value
}
var file_skill_proto_depIdxs = []int32{
	6,  // 0: engine.DeleteSkillAgentResponse.items:type_name -> engine.SkillAgentItem
	17, // 1: engine.PatchSkillAgentRequest.skill:type_name -> engine.Lookup
	18, // 2: engine.PatchSkillAgentRequest.capacity:type_name -> google.protobuf.Int32Value
	6,  // 3: engine.CreateSkillAgentResponse.items:type_name -> engine.SkillAgentItem
	6,  // 4: engine.PatchSkillAgentResponse.items:type_name -> engine.SkillAgentItem
	17, // 5: engine.CreateSkillAgentRequest.agent:type_name -> engine.Lookup
	18, // 6: engine.CreateSkillAgentRequest.capacity:type_name -> google.protobuf.Int32Value
	17, // 7: engine.SkillAgentItem.skill:type_name -> engine.Lookup
	18, // 8: engine.SkillAgentItem.capacity:type_name -> google.protobuf.Int32Value
	17, // 9: engine.SkillAgentItem.agent:type_name -> engine.Lookup
	17, // 10: engine.SkillAgentItem.team:type_name -> engine.Lookup
	6,  // 11: engine.ListSkillAgent.items:type_name -> engine.SkillAgentItem
	16, // 12: engine.ListSkillAgent.aggs:type_name -> engine.ListSkillAgent.ListSkillAgg
	17, // 13: engine.Skill.created_by:type_name -> engine.Lookup
	17, // 14: engine.Skill.updated_by:type_name -> engine.Lookup
	14, // 15: engine.ListSkill.items:type_name -> engine.Skill
	12, // 16: engine.SkillService.CreateSkill:input_type -> engine.CreateSkillRequest
	11, // 17: engine.SkillService.SearchSkill:input_type -> engine.SearchSkillRequest
	9,  // 18: engine.SkillService.ReadSkill:input_type -> engine.ReadSkillRequest
	13, // 19: engine.SkillService.UpdateSkill:input_type -> engine.UpdateSkillRequest
	10, // 20: engine.SkillService.DeleteSkill:input_type -> engine.DeleteSkillRequest
	7,  // 21: engine.SkillService.SearchSkillAgent:input_type -> engine.SearchSkillAgentRequest
	5,  // 22: engine.SkillService.CreateSkillAgent:input_type -> engine.CreateSkillAgentRequest
	2,  // 23: engine.SkillService.PatchSkillAgent:input_type -> engine.PatchSkillAgentRequest
	0,  // 24: engine.SkillService.DeleteSkillAgent:input_type -> engine.DeleteSkillAgentRequest
	14, // 25: engine.SkillService.CreateSkill:output_type -> engine.Skill
	15, // 26: engine.SkillService.SearchSkill:output_type -> engine.ListSkill
	14, // 27: engine.SkillService.ReadSkill:output_type -> engine.Skill
	14, // 28: engine.SkillService.UpdateSkill:output_type -> engine.Skill
	14, // 29: engine.SkillService.DeleteSkill:output_type -> engine.Skill
	8,  // 30: engine.SkillService.SearchSkillAgent:output_type -> engine.ListSkillAgent
	3,  // 31: engine.SkillService.CreateSkillAgent:output_type -> engine.CreateSkillAgentResponse
	4,  // 32: engine.SkillService.PatchSkillAgent:output_type -> engine.PatchSkillAgentResponse
	1,  // 33: engine.SkillService.DeleteSkillAgent:output_type -> engine.DeleteSkillAgentResponse
	25, // [25:34] is the sub-list for method output_type
	16, // [16:25] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_skill_proto_init() }
func file_skill_proto_init() {
	if File_skill_proto != nil {
		return
	}
	file_const_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skill_proto_rawDesc), len(file_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skill_proto_goTypes,
		DependencyIndexes: file_skill_proto_depIdxs,
		MessageInfos:      file_skill_proto_msgTypes,
	}.Build()
	File_skill_proto = out.File
	file_skill_proto_goTypes = nil
	file_skill_proto_depIdxs = nil
}
