// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: system_settings.proto

package engine

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemSettingName int32

const (
	SystemSettingName_empty_system_settings_name  SystemSettingName = 0
	SystemSettingName_enable_omnichannel          SystemSettingName = 1
	SystemSettingName_member_chunk_size           SystemSettingName = 2
	SystemSettingName_amd_cancel_not_human        SystemSettingName = 3
	SystemSettingName_scheme_version_limit        SystemSettingName = 4
	SystemSettingName_enable_2fa                  SystemSettingName = 5
	SystemSettingName_export_settings             SystemSettingName = 6
	SystemSettingName_search_number_length        SystemSettingName = 7
	SystemSettingName_chat_ai_connection          SystemSettingName = 8
	SystemSettingName_password_reg_exp            SystemSettingName = 9
	SystemSettingName_password_validation_text    SystemSettingName = 10
	SystemSettingName_autolink_call_to_contact    SystemSettingName = 11
	SystemSettingName_period_to_playback_records  SystemSettingName = 12
	SystemSettingName_is_fulltext_search_enabled  SystemSettingName = 13
	SystemSettingName_wbt_hide_contact            SystemSettingName = 14
	SystemSettingName_show_full_contact           SystemSettingName = 15
	SystemSettingName_call_end_sound_notification SystemSettingName = 16
	SystemSettingName_call_end_push_notification  SystemSettingName = 17
	SystemSettingName_chat_end_sound_notification SystemSettingName = 18
	SystemSettingName_chat_end_push_notification  SystemSettingName = 19
	SystemSettingName_task_end_sound_notification SystemSettingName = 20
	SystemSettingName_task_end_push_notification  SystemSettingName = 21
	SystemSettingName_push_notification_timeout   SystemSettingName = 22
	SystemSettingName_labels_to_limit_contacts    SystemSettingName = 23
)

// Enum value maps for SystemSettingName.
var (
	SystemSettingName_name = map[int32]string{
		0:  "empty_system_settings_name",
		1:  "enable_omnichannel",
		2:  "member_chunk_size",
		3:  "amd_cancel_not_human",
		4:  "scheme_version_limit",
		5:  "enable_2fa",
		6:  "export_settings",
		7:  "search_number_length",
		8:  "chat_ai_connection",
		9:  "password_reg_exp",
		10: "password_validation_text",
		11: "autolink_call_to_contact",
		12: "period_to_playback_records",
		13: "is_fulltext_search_enabled",
		14: "wbt_hide_contact",
		15: "show_full_contact",
		16: "call_end_sound_notification",
		17: "call_end_push_notification",
		18: "chat_end_sound_notification",
		19: "chat_end_push_notification",
		20: "task_end_sound_notification",
		21: "task_end_push_notification",
		22: "push_notification_timeout",
		23: "labels_to_limit_contacts",
	}
	SystemSettingName_value = map[string]int32{
		"empty_system_settings_name":  0,
		"enable_omnichannel":          1,
		"member_chunk_size":           2,
		"amd_cancel_not_human":        3,
		"scheme_version_limit":        4,
		"enable_2fa":                  5,
		"export_settings":             6,
		"search_number_length":        7,
		"chat_ai_connection":          8,
		"password_reg_exp":            9,
		"password_validation_text":    10,
		"autolink_call_to_contact":    11,
		"period_to_playback_records":  12,
		"is_fulltext_search_enabled":  13,
		"wbt_hide_contact":            14,
		"show_full_contact":           15,
		"call_end_sound_notification": 16,
		"call_end_push_notification":  17,
		"chat_end_sound_notification": 18,
		"chat_end_push_notification":  19,
		"task_end_sound_notification": 20,
		"task_end_push_notification":  21,
		"push_notification_timeout":   22,
		"labels_to_limit_contacts":    23,
	}
)

func (x SystemSettingName) Enum() *SystemSettingName {
	p := new(SystemSettingName)
	*p = x
	return p
}

func (x SystemSettingName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemSettingName) Descriptor() protoreflect.EnumDescriptor {
	return file_system_settings_proto_enumTypes[0].Descriptor()
}

func (SystemSettingName) Type() protoreflect.EnumType {
	return &file_system_settings_proto_enumTypes[0]
}

func (x SystemSettingName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemSettingName.Descriptor instead.
func (SystemSettingName) EnumDescriptor() ([]byte, []int) {
	return file_system_settings_proto_rawDescGZIP(), []int{0}
}

type SearchAvailableSystemSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Q             string                 `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Fields        []string               `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAvailableSystemSettingRequest) Reset() {
	*x = SearchAvailableSystemSettingRequest{}
	mi := &file_system_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAvailableSystemSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAvailableSystemSettingRequest) ProtoMessage() {}

func (x *SearchAvailableSystemSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAvailableSystemSettingRequest.ProtoReflect.Descriptor instead.
func (*SearchAvailableSystemSettingRequest) Descriptor() ([]byte, []int) {
	return file_system_settings_proto_rawDescGZIP(), []int{0}
}

func (x *SearchAvailableSystemSettingRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchAvailableSystemSettingRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchAvailableSystemSettingRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchAvailableSystemSettingRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchAvailableSystemSettingRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type AvailableSystemSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableSystemSetting) Reset() {
	*x = AvailableSystemSetting{}
	mi := &file_system_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableSystemSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableSystemSetting) ProtoMessage() {}

func (x *AvailableSystemSetting) ProtoReflect() protoreflect.Message {
	mi := &file_system_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableSystemSetting.ProtoReflect.Descriptor instead.
func (*AvailableSystemSetting) Descriptor() ([]byte, []int) {
	return file_system_settings_proto_rawDescGZIP(), []int{1}
}

func (x *AvailableSystemSetting) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListAvailableSystemSetting struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Next          bool                      `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*AvailableSystemSetting `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableSystemSetting) Reset() {
	*x = ListAvailableSystemSetting{}
	mi := &file_system_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableSystemSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableSystemSetting) ProtoMessage() {}

func (x *ListAvailableSystemSetting) ProtoReflect() protoreflect.Message {
	mi := &file_system_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableSystemSetting.ProtoReflect.Descriptor instead.
func (*ListAvailableSystemSetting) Descriptor() ([]byte, []int) {
	return file_system_settings_proto_rawDescGZIP(), []int{2}
}

func (x *ListAvailableSystemSetting) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *ListAvailableSystemSetting) GetItems() []*AvailableSystemSetting {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteSystemSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSystemSettingRequest) Reset() {
	*x = DeleteSystemSettingRequest{}
	mi := &file_system_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSystemSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSystemSettingRequest) ProtoMessage() {}

func (x *DeleteSystemSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSystemSettingRequest.ProtoReflect.Descriptor instead.
func (*DeleteSystemSettingRequest) Descriptor() ([]byte, []int) {
	return file_system_settings_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSystemSettingRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PatchSystemSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchSystemSettingRequest) Reset() {
	*x = PatchSystemSettingRequest{}
	mi := &file_system_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchSystemSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchSystemSettingRequest) ProtoMessage() {}

func (x *PatchSystemSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchSystemSettingRequest.ProtoReflect.Descriptor instead.
func (*PatchSystemSettingRequest) Descriptor() ([]byte, []int) {
	return file_system_settings_proto_rawDescGZIP(), []int{4}
}

func (x *PatchSystemSettingRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *PatchSystemSettingRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchSystemSettingRequest) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type UpdateSystemSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSystemSettingRequest) Reset() {
	*x = UpdateSystemSettingRequest{}
	mi := &file_system_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSystemSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSystemSettingRequest) ProtoMessage() {}

func (x *UpdateSystemSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSystemSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateSystemSettingRequest) Descriptor() ([]byte, []int) {
	return file_system_settings_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSystemSettingRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSystemSettingRequest) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type ReadSystemSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSystemSettingRequest) Reset() {
	*x = ReadSystemSettingRequest{}
	mi := &file_system_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSystemSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSystemSettingRequest) ProtoMessage() {}

func (x *ReadSystemSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSystemSettingRequest.ProtoReflect.Descriptor instead.
func (*ReadSystemSettingRequest) Descriptor() ([]byte, []int) {
	return file_system_settings_proto_rawDescGZIP(), []int{6}
}

func (x *ReadSystemSettingRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateSystemSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          SystemSettingName      `protobuf:"varint,1,opt,name=name,proto3,enum=engine.SystemSettingName" json:"name,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSystemSettingRequest) Reset() {
	*x = CreateSystemSettingRequest{}
	mi := &file_system_settings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSystemSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSystemSettingRequest) ProtoMessage() {}

func (x *CreateSystemSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_settings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSystemSettingRequest.ProtoReflect.Descriptor instead.
func (*CreateSystemSettingRequest) Descriptor() ([]byte, []int) {
	return file_system_settings_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSystemSettingRequest) GetName() SystemSettingName {
	if x != nil {
		return x.Name
	}
	return SystemSettingName_empty_system_settings_name
}

func (x *CreateSystemSettingRequest) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type SystemSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          SystemSettingName      `protobuf:"varint,2,opt,name=name,proto3,enum=engine.SystemSettingName" json:"name,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemSetting) Reset() {
	*x = SystemSetting{}
	mi := &file_system_settings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemSetting) ProtoMessage() {}

func (x *SystemSetting) ProtoReflect() protoreflect.Message {
	mi := &file_system_settings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemSetting.ProtoReflect.Descriptor instead.
func (*SystemSetting) Descriptor() ([]byte, []int) {
	return file_system_settings_proto_rawDescGZIP(), []int{8}
}

func (x *SystemSetting) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SystemSetting) GetName() SystemSettingName {
	if x != nil {
		return x.Name
	}
	return SystemSettingName_empty_system_settings_name
}

func (x *SystemSetting) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type SearchSystemSettingRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Page   int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size   int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Q      string                 `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	Sort   string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Fields []string               `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	// Filter by setting names
	Name          []SystemSettingName `protobuf:"varint,7,rep,packed,name=name,proto3,enum=engine.SystemSettingName" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSystemSettingRequest) Reset() {
	*x = SearchSystemSettingRequest{}
	mi := &file_system_settings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSystemSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSystemSettingRequest) ProtoMessage() {}

func (x *SearchSystemSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_settings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSystemSettingRequest.ProtoReflect.Descriptor instead.
func (*SearchSystemSettingRequest) Descriptor() ([]byte, []int) {
	return file_system_settings_proto_rawDescGZIP(), []int{9}
}

func (x *SearchSystemSettingRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchSystemSettingRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchSystemSettingRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchSystemSettingRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchSystemSettingRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SearchSystemSettingRequest) GetName() []SystemSettingName {
	if x != nil {
		return x.Name
	}
	return nil
}

type ListSystemSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Next          bool                   `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*SystemSetting       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSystemSetting) Reset() {
	*x = ListSystemSetting{}
	mi := &file_system_settings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSystemSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemSetting) ProtoMessage() {}

func (x *ListSystemSetting) ProtoReflect() protoreflect.Message {
	mi := &file_system_settings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemSetting.ProtoReflect.Descriptor instead.
func (*ListSystemSetting) Descriptor() ([]byte, []int) {
	return file_system_settings_proto_rawDescGZIP(), []int{10}
}

func (x *ListSystemSetting) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *ListSystemSetting) GetItems() []*SystemSetting {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_system_settings_proto protoreflect.FileDescriptor

const file_system_settings_proto_rawDesc = "" +
	"\n" +
	"\x15system_settings.proto\x12\x06engine\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x87\x01\n" +
	"#SearchAvailableSystemSettingRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\f\n" +
	"\x01q\x18\x03 \x01(\tR\x01q\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\x12\x16\n" +
	"\x06fields\x18\x06 \x03(\tR\x06fields\",\n" +
	"\x16AvailableSystemSetting\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"f\n" +
	"\x1aListAvailableSystemSetting\x12\x12\n" +
	"\x04next\x18\x01 \x01(\bR\x04next\x124\n" +
	"\x05items\x18\x02 \x03(\v2\x1e.engine.AvailableSystemSettingR\x05items\",\n" +
	"\x1aDeleteSystemSettingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"q\n" +
	"\x19PatchSystemSettingRequest\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\"Z\n" +
	"\x1aUpdateSystemSettingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value\"*\n" +
	"\x18ReadSystemSettingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"y\n" +
	"\x1aCreateSystemSettingRequest\x12-\n" +
	"\x04name\x18\x01 \x01(\x0e2\x19.engine.SystemSettingNameR\x04name\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value\"|\n" +
	"\rSystemSetting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12-\n" +
	"\x04name\x18\x02 \x01(\x0e2\x19.engine.SystemSettingNameR\x04name\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\"\xad\x01\n" +
	"\x1aSearchSystemSettingRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\f\n" +
	"\x01q\x18\x03 \x01(\tR\x01q\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\x12\x16\n" +
	"\x06fields\x18\x06 \x03(\tR\x06fields\x12-\n" +
	"\x04name\x18\a \x03(\x0e2\x19.engine.SystemSettingNameR\x04name\"T\n" +
	"\x11ListSystemSetting\x12\x12\n" +
	"\x04next\x18\x01 \x01(\bR\x04next\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.engine.SystemSettingR\x05items*\xac\x05\n" +
	"\x11SystemSettingName\x12\x1e\n" +
	"\x1aempty_system_settings_name\x10\x00\x12\x16\n" +
	"\x12enable_omnichannel\x10\x01\x12\x15\n" +
	"\x11member_chunk_size\x10\x02\x12\x18\n" +
	"\x14amd_cancel_not_human\x10\x03\x12\x18\n" +
	"\x14scheme_version_limit\x10\x04\x12\x0e\n" +
	"\n" +
	"enable_2fa\x10\x05\x12\x13\n" +
	"\x0fexport_settings\x10\x06\x12\x18\n" +
	"\x14search_number_length\x10\a\x12\x16\n" +
	"\x12chat_ai_connection\x10\b\x12\x14\n" +
	"\x10password_reg_exp\x10\t\x12\x1c\n" +
	"\x18password_validation_text\x10\n" +
	"\x12\x1c\n" +
	"\x18autolink_call_to_contact\x10\v\x12\x1e\n" +
	"\x1aperiod_to_playback_records\x10\f\x12\x1e\n" +
	"\x1ais_fulltext_search_enabled\x10\r\x12\x14\n" +
	"\x10wbt_hide_contact\x10\x0e\x12\x15\n" +
	"\x11show_full_contact\x10\x0f\x12\x1f\n" +
	"\x1bcall_end_sound_notification\x10\x10\x12\x1e\n" +
	"\x1acall_end_push_notification\x10\x11\x12\x1f\n" +
	"\x1bchat_end_sound_notification\x10\x12\x12\x1e\n" +
	"\x1achat_end_push_notification\x10\x13\x12\x1f\n" +
	"\x1btask_end_sound_notification\x10\x14\x12\x1e\n" +
	"\x1atask_end_push_notification\x10\x15\x12\x1d\n" +
	"\x19push_notification_timeout\x10\x16\x12\x1c\n" +
	"\x18labels_to_limit_contacts\x10\x172\x9e\x06\n" +
	"\x14SystemSettingService\x12f\n" +
	"\x13CreateSystemSetting\x12\".engine.CreateSystemSettingRequest\x1a\x15.engine.SystemSetting\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/settings\x12g\n" +
	"\x13SearchSystemSetting\x12\".engine.SearchSystemSettingRequest\x1a\x19.engine.ListSystemSetting\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/settings\x12\x8c\x01\n" +
	"\x1cSearchAvailableSystemSetting\x12+.engine.SearchAvailableSystemSettingRequest\x1a\".engine.ListAvailableSystemSetting\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/settings/available\x12d\n" +
	"\x11ReadSystemSetting\x12 .engine.ReadSystemSettingRequest\x1a\x15.engine.SystemSetting\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/settings/{id}\x12k\n" +
	"\x13UpdateSystemSetting\x12\".engine.UpdateSystemSettingRequest\x1a\x15.engine.SystemSetting\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/settings/{id}\x12i\n" +
	"\x12PatchSystemSetting\x12!.engine.PatchSystemSettingRequest\x1a\x15.engine.SystemSetting\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*2\x0e/settings/{id}\x12h\n" +
	"\x13DeleteSystemSetting\x12\".engine.DeleteSystemSettingRequest\x1a\x15.engine.SystemSetting\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/settings/{id}B\"Z github.com/webitel/protos/engineb\x06proto3"

var (
	file_system_settings_proto_rawDescOnce sync.Once
	file_system_settings_proto_rawDescData []byte
)

func file_system_settings_proto_rawDescGZIP() []byte {
	file_system_settings_proto_rawDescOnce.Do(func() {
		file_system_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_settings_proto_rawDesc), len(file_system_settings_proto_rawDesc)))
	})
	return file_system_settings_proto_rawDescData
}

var file_system_settings_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_system_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_system_settings_proto_goTypes = []any{
	(SystemSettingName)(0),                      // 0: engine.SystemSettingName
	(*SearchAvailableSystemSettingRequest)(nil), // 1: engine.SearchAvailableSystemSettingRequest
	(*AvailableSystemSetting)(nil),              // 2: engine.AvailableSystemSetting
	(*ListAvailableSystemSetting)(nil),          // 3: engine.ListAvailableSystemSetting
	(*DeleteSystemSettingRequest)(nil),          // 4: engine.DeleteSystemSettingRequest
	(*PatchSystemSettingRequest)(nil),           // 5: engine.PatchSystemSettingRequest
	(*UpdateSystemSettingRequest)(nil),          // 6: engine.UpdateSystemSettingRequest
	(*ReadSystemSettingRequest)(nil),            // 7: engine.ReadSystemSettingRequest
	(*CreateSystemSettingRequest)(nil),          // 8: engine.CreateSystemSettingRequest
	(*SystemSetting)(nil),                       // 9: engine.SystemSetting
	(*SearchSystemSettingRequest)(nil),          // 10: engine.SearchSystemSettingRequest
	(*ListSystemSetting)(nil),                   // 11: engine.ListSystemSetting
	(*structpb.Value)(nil),                      // 12: google.protobuf.Value
}
var file_system_settings_proto_depIdxs = []int32{
	2,  // 0: engine.ListAvailableSystemSetting.items:type_name -> engine.AvailableSystemSetting
	12, // 1: engine.PatchSystemSettingRequest.value:type_name -> google.protobuf.Value
	12, // 2: engine.UpdateSystemSettingRequest.value:type_name -> google.protobuf.Value
	0,  // 3: engine.CreateSystemSettingRequest.name:type_name -> engine.SystemSettingName
	12, // 4: engine.CreateSystemSettingRequest.value:type_name -> google.protobuf.Value
	0,  // 5: engine.SystemSetting.name:type_name -> engine.SystemSettingName
	12, // 6: engine.SystemSetting.value:type_name -> google.protobuf.Value
	0,  // 7: engine.SearchSystemSettingRequest.name:type_name -> engine.SystemSettingName
	9,  // 8: engine.ListSystemSetting.items:type_name -> engine.SystemSetting
	8,  // 9: engine.SystemSettingService.CreateSystemSetting:input_type -> engine.CreateSystemSettingRequest
	10, // 10: engine.SystemSettingService.SearchSystemSetting:input_type -> engine.SearchSystemSettingRequest
	1,  // 11: engine.SystemSettingService.SearchAvailableSystemSetting:input_type -> engine.SearchAvailableSystemSettingRequest
	7,  // 12: engine.SystemSettingService.ReadSystemSetting:input_type -> engine.ReadSystemSettingRequest
	6,  // 13: engine.SystemSettingService.UpdateSystemSetting:input_type -> engine.UpdateSystemSettingRequest
	5,  // 14: engine.SystemSettingService.PatchSystemSetting:input_type -> engine.PatchSystemSettingRequest
	4,  // 15: engine.SystemSettingService.DeleteSystemSetting:input_type -> engine.DeleteSystemSettingRequest
	9,  // 16: engine.SystemSettingService.CreateSystemSetting:output_type -> engine.SystemSetting
	11, // 17: engine.SystemSettingService.SearchSystemSetting:output_type -> engine.ListSystemSetting
	3,  // 18: engine.SystemSettingService.SearchAvailableSystemSetting:output_type -> engine.ListAvailableSystemSetting
	9,  // 19: engine.SystemSettingService.ReadSystemSetting:output_type -> engine.SystemSetting
	9,  // 20: engine.SystemSettingService.UpdateSystemSetting:output_type -> engine.SystemSetting
	9,  // 21: engine.SystemSettingService.PatchSystemSetting:output_type -> engine.SystemSetting
	9,  // 22: engine.SystemSettingService.DeleteSystemSetting:output_type -> engine.SystemSetting
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_system_settings_proto_init() }
func file_system_settings_proto_init() {
	if File_system_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_settings_proto_rawDesc), len(file_system_settings_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_settings_proto_goTypes,
		DependencyIndexes: file_system_settings_proto_depIdxs,
		EnumInfos:         file_system_settings_proto_enumTypes,
		MessageInfos:      file_system_settings_proto_msgTypes,
	}.Build()
	File_system_settings_proto = out.File
	file_system_settings_proto_goTypes = nil
	file_system_settings_proto_depIdxs = nil
}
