// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: knowledgebase/fields.proto

package spaces

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lookup reference information.
// Simplified search filter to uniquely identify related object.
type Lookup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference Object unique ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Reference Object well-known type.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Reference Object display name.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lookup) Reset() {
	*x = Lookup{}
	mi := &file_knowledgebase_fields_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lookup) ProtoMessage() {}

func (x *Lookup) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_fields_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lookup.ProtoReflect.Descriptor instead.
func (*Lookup) Descriptor() ([]byte, []int) {
	return file_knowledgebase_fields_proto_rawDescGZIP(), []int{0}
}

func (x *Lookup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lookup) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Lookup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_knowledgebase_fields_proto protoreflect.FileDescriptor

const file_knowledgebase_fields_proto_rawDesc = "" +
	"\n" +
	"\x1aknowledgebase/fields.proto\x12\x15webitel.knowledgebase\"@\n" +
	"\x06Lookup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04nameB\xbb\x01\n" +
	"\x19com.webitel.knowledgebaseB\vFieldsProtoP\x01Z\x1cwebitel.go/api/spaces;spaces\xa2\x02\x03WKX\xaa\x02\x15Webitel.Knowledgebase\xca\x02\x15Webitel\\Knowledgebase\xe2\x02!Webitel\\Knowledgebase\\GPBMetadata\xea\x02\x16Webitel::Knowledgebaseb\x06proto3"

var (
	file_knowledgebase_fields_proto_rawDescOnce sync.Once
	file_knowledgebase_fields_proto_rawDescData []byte
)

func file_knowledgebase_fields_proto_rawDescGZIP() []byte {
	file_knowledgebase_fields_proto_rawDescOnce.Do(func() {
		file_knowledgebase_fields_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_knowledgebase_fields_proto_rawDesc), len(file_knowledgebase_fields_proto_rawDesc)))
	})
	return file_knowledgebase_fields_proto_rawDescData
}

var file_knowledgebase_fields_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_knowledgebase_fields_proto_goTypes = []any{
	(*Lookup)(nil), // 0: webitel.knowledgebase.Lookup
}
var file_knowledgebase_fields_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_knowledgebase_fields_proto_init() }
func file_knowledgebase_fields_proto_init() {
	if File_knowledgebase_fields_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_knowledgebase_fields_proto_rawDesc), len(file_knowledgebase_fields_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_knowledgebase_fields_proto_goTypes,
		DependencyIndexes: file_knowledgebase_fields_proto_depIdxs,
		MessageInfos:      file_knowledgebase_fields_proto_msgTypes,
	}.Build()
	File_knowledgebase_fields_proto = out.File
	file_knowledgebase_fields_proto_goTypes = nil
	file_knowledgebase_fields_proto_depIdxs = nil
}
