// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: class.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectClass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`      // (class::object).id
	Class         string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"` // (class::object).name
	Abac          bool                   `protobuf:"varint,3,opt,name=abac,proto3" json:"abac,omitempty"`  // [a]ttribute-[b]ased [a]ccess [c]ontrol
	Obac          bool                   `protobuf:"varint,4,opt,name=obac,proto3" json:"obac,omitempty"`  // [o]peration-[b]ased [a]ccess [c]ontrol (from::collection.dal)
	Rbac          bool                   `protobuf:"varint,5,opt,name=rbac,proto3" json:"rbac,omitempty"`  // [r]ecord-[b]ased [a]ccess [c]ontrol (from::resource.acl)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectClass) Reset() {
	*x = ObjectClass{}
	mi := &file_class_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectClass) ProtoMessage() {}

func (x *ObjectClass) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectClass.ProtoReflect.Descriptor instead.
func (*ObjectClass) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectClass) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ObjectClass) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ObjectClass) GetAbac() bool {
	if x != nil {
		return x.Abac
	}
	return false
}

func (x *ObjectClass) GetObac() bool {
	if x != nil {
		return x.Obac
	}
	return false
}

func (x *ObjectClass) GetRbac() bool {
	if x != nil {
		return x.Rbac
	}
	return false
}

type ReadClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Class         string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"` // [filter]: like '%class%'
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`      // [filter]: obj.id = id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadClassRequest) Reset() {
	*x = ReadClassRequest{}
	mi := &file_class_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadClassRequest) ProtoMessage() {}

func (x *ReadClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadClassRequest.ProtoReflect.Descriptor instead.
func (*ReadClassRequest) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{1}
}

func (x *ReadClassRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ReadClassRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ReadClassRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         *ObjectClass           `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadClassResponse) Reset() {
	*x = ReadClassResponse{}
	mi := &file_class_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadClassResponse) ProtoMessage() {}

func (x *ReadClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadClassResponse.ProtoReflect.Descriptor instead.
func (*ReadClassResponse) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{2}
}

func (x *ReadClassResponse) GetClass() *ObjectClass {
	if x != nil {
		return x.Class
	}
	return nil
}

type UpdateClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"` // TO BE REMOVED // bound to session.domain.id
	Class         *ObjectClass           `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Fields        []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"` // PATCH: partial update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClassRequest) Reset() {
	*x = UpdateClassRequest{}
	mi := &file_class_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClassRequest) ProtoMessage() {}

func (x *UpdateClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClassRequest.ProtoReflect.Descriptor instead.
func (*UpdateClassRequest) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateClassRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UpdateClassRequest) GetClass() *ObjectClass {
	if x != nil {
		return x.Class
	}
	return nil
}

func (x *UpdateClassRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type UpdateClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         *ObjectClass           `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"` // updated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClassResponse) Reset() {
	*x = UpdateClassResponse{}
	mi := &file_class_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClassResponse) ProtoMessage() {}

func (x *UpdateClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClassResponse.ProtoReflect.Descriptor instead.
func (*UpdateClassResponse) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateClassResponse) GetClass() *ObjectClass {
	if x != nil {
		return x.Class
	}
	return nil
}

type SearchClassesRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Domain string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"` // TO BE REMOVED // bound to session.domain.id
	Class  string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`   // [filter]: like '%class%'
	// int64 id = 3;  // [filter]: obj.id = id
	// controls
	Fields        []string `protobuf:"bytes,10,rep,name=fields,proto3" json:"fields,omitempty"` // output
	Sort          []string `protobuf:"bytes,11,rep,name=sort,proto3" json:"sort,omitempty"`     // sort: "field" asc; "!field" desc
	Page          int32    `protobuf:"varint,12,opt,name=page,proto3" json:"page,omitempty"`    // page number
	Size          int32    `protobuf:"varint,13,opt,name=size,proto3" json:"size,omitempty"`    // page size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchClassesRequest) Reset() {
	*x = SearchClassesRequest{}
	mi := &file_class_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchClassesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchClassesRequest) ProtoMessage() {}

func (x *SearchClassesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchClassesRequest.ProtoReflect.Descriptor instead.
func (*SearchClassesRequest) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{5}
}

func (x *SearchClassesRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SearchClassesRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *SearchClassesRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SearchClassesRequest) GetSort() []string {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *SearchClassesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchClassesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SearchClassesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,10,opt,name=page,proto3" json:"page,omitempty"` // select: offset {page}
	Size          int32                  `protobuf:"varint,11,opt,name=size,proto3" json:"size,omitempty"` // search: limit {size}
	Next          bool                   `protobuf:"varint,12,opt,name=next,proto3" json:"next,omitempty"` // search: has {next} page ?
	Items         []*ObjectClass         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchClassesResponse) Reset() {
	*x = SearchClassesResponse{}
	mi := &file_class_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchClassesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchClassesResponse) ProtoMessage() {}

func (x *SearchClassesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_class_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchClassesResponse.ProtoReflect.Descriptor instead.
func (*SearchClassesResponse) Descriptor() ([]byte, []int) {
	return file_class_proto_rawDescGZIP(), []int{6}
}

func (x *SearchClassesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchClassesResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchClassesResponse) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *SearchClassesResponse) GetItems() []*ObjectClass {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_class_proto protoreflect.FileDescriptor

const file_class_proto_rawDesc = "" +
	"\n" +
	"\vclass.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\"o\n" +
	"\vObjectClass\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12\x12\n" +
	"\x04abac\x18\x03 \x01(\bR\x04abac\x12\x12\n" +
	"\x04obac\x18\x04 \x01(\bR\x04obac\x12\x12\n" +
	"\x04rbac\x18\x05 \x01(\bR\x04rbac\"P\n" +
	"\x10ReadClassRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\";\n" +
	"\x11ReadClassResponse\x12&\n" +
	"\x05class\x18\x01 \x01(\v2\x10.api.ObjectClassR\x05class\"l\n" +
	"\x12UpdateClassRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12&\n" +
	"\x05class\x18\x02 \x01(\v2\x10.api.ObjectClassR\x05class\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\"=\n" +
	"\x13UpdateClassResponse\x12&\n" +
	"\x05class\x18\x01 \x01(\v2\x10.api.ObjectClassR\x05class\"\x98\x01\n" +
	"\x14SearchClassesRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12\x16\n" +
	"\x06fields\x18\n" +
	" \x03(\tR\x06fields\x12\x12\n" +
	"\x04sort\x18\v \x03(\tR\x04sort\x12\x12\n" +
	"\x04page\x18\f \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\r \x01(\x05R\x04size\"{\n" +
	"\x15SearchClassesResponse\x12\x12\n" +
	"\x04page\x18\n" +
	" \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\v \x01(\x05R\x04size\x12\x12\n" +
	"\x04next\x18\f \x01(\bR\x04next\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.api.ObjectClassR\x05items2\xb6\x02\n" +
	"\aClasses\x12R\n" +
	"\tReadClass\x12\x15.api.ReadClassRequest\x1a\x16.api.ReadClassResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/objclass/{id}\x12|\n" +
	"\vUpdateClass\x12\x17.api.UpdateClassRequest\x1a\x18.api.UpdateClassResponse\":\x82\xd3\xe4\x93\x024:\x01*Z\x19:\x01*2\x14/objclass/{class.id}\x1a\x14/objclass/{class.id}\x12Y\n" +
	"\rSearchClasses\x12\x19.api.SearchClassesRequest\x1a\x1a.api.SearchClassesResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/objclassBU\n" +
	"\acom.apiB\n" +
	"ClassProtoP\x01Z\x12webitel.go/api;api\xa2\x02\x03AXX\xaa\x02\x03Api\xca\x02\x03Api\xe2\x02\x0fApi\\GPBMetadata\xea\x02\x03Apib\x06proto3"

var (
	file_class_proto_rawDescOnce sync.Once
	file_class_proto_rawDescData []byte
)

func file_class_proto_rawDescGZIP() []byte {
	file_class_proto_rawDescOnce.Do(func() {
		file_class_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_class_proto_rawDesc), len(file_class_proto_rawDesc)))
	})
	return file_class_proto_rawDescData
}

var file_class_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_class_proto_goTypes = []any{
	(*ObjectClass)(nil),           // 0: api.ObjectClass
	(*ReadClassRequest)(nil),      // 1: api.ReadClassRequest
	(*ReadClassResponse)(nil),     // 2: api.ReadClassResponse
	(*UpdateClassRequest)(nil),    // 3: api.UpdateClassRequest
	(*UpdateClassResponse)(nil),   // 4: api.UpdateClassResponse
	(*SearchClassesRequest)(nil),  // 5: api.SearchClassesRequest
	(*SearchClassesResponse)(nil), // 6: api.SearchClassesResponse
}
var file_class_proto_depIdxs = []int32{
	0, // 0: api.ReadClassResponse.class:type_name -> api.ObjectClass
	0, // 1: api.UpdateClassRequest.class:type_name -> api.ObjectClass
	0, // 2: api.UpdateClassResponse.class:type_name -> api.ObjectClass
	0, // 3: api.SearchClassesResponse.items:type_name -> api.ObjectClass
	1, // 4: api.Classes.ReadClass:input_type -> api.ReadClassRequest
	3, // 5: api.Classes.UpdateClass:input_type -> api.UpdateClassRequest
	5, // 6: api.Classes.SearchClasses:input_type -> api.SearchClassesRequest
	2, // 7: api.Classes.ReadClass:output_type -> api.ReadClassResponse
	4, // 8: api.Classes.UpdateClass:output_type -> api.UpdateClassResponse
	6, // 9: api.Classes.SearchClasses:output_type -> api.SearchClassesResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_class_proto_init() }
func file_class_proto_init() {
	if File_class_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_class_proto_rawDesc), len(file_class_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_class_proto_goTypes,
		DependencyIndexes: file_class_proto_depIdxs,
		MessageInfos:      file_class_proto_msgTypes,
	}.Build()
	File_class_proto = out.File
	file_class_proto_goTypes = nil
	file_class_proto_depIdxs = nil
}
