// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: contacts/contacts.proto

package contacts

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/visibility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Contact dataset.
type ContactList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contact(s) dataset page.
	Data []*Contact `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// The page number of the partial result.
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Indicates that this is a partial result.
	// More data available upon query: ?size=${data.len}&page=${page++}
	Next          bool `protobuf:"varint,3,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactList) Reset() {
	*x = ContactList{}
	mi := &file_contacts_contacts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactList) ProtoMessage() {}

func (x *ContactList) ProtoReflect() protoreflect.Message {
	mi := &file_contacts_contacts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactList.ProtoReflect.Descriptor instead.
func (*ContactList) Descriptor() ([]byte, []int) {
	return file_contacts_contacts_proto_rawDescGZIP(), []int{0}
}

func (x *ContactList) GetData() []*Contact {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ContactList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ContactList) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

type LocateContactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source Fields to return into result.
	Fields []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	// The Contact source IDentifier.
	// Accept: `etag` (obsolete+) or `id`.
	Etag string `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	// The requirement of a special access mode to the Source.
	Mode          AccessMode `protobuf:"varint,3,opt,name=mode,proto3,enum=webitel.contacts.AccessMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateContactRequest) Reset() {
	*x = LocateContactRequest{}
	mi := &file_contacts_contacts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateContactRequest) ProtoMessage() {}

func (x *LocateContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contacts_contacts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateContactRequest.ProtoReflect.Descriptor instead.
func (*LocateContactRequest) Descriptor() ([]byte, []int) {
	return file_contacts_contacts_proto_rawDescGZIP(), []int{1}
}

func (x *LocateContactRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *LocateContactRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *LocateContactRequest) GetMode() AccessMode {
	if x != nil {
		return x.Mode
	}
	return AccessMode_READ
}

type SearchContactsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page number of result records.   _default(1); offset=(size*(page-1));_
	//
	// ```javascript
	// let
	//
	//	  offset = 0
	//	, page = req.page
	//
	// ;
	// if (page <= 0)
	//
	//	page = 1;
	//
	// if (page > 1)
	//
	//	offset = ((page-1)*size);
	//
	// // . . .
	// ```
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Limit of result page records count.   _default(16); limit=(size<=0?-1:size+1);_
	//
	// ```javascript
	// const
	//
	//	  default = 16
	//	, maximum = 32
	//
	// ;
	// let limit = req.size;
	// if (limit <= 0)
	//
	//	limit = default;
	//
	// if (maximum < limit)
	//
	//	limit = maximum;
	//
	// // . . .
	// ```
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// Search term:
	// `?` - matches any character
	// `*` - matches 0 or more characters
	// Used to query records within a set of `qin` fields, eg: name,emails{type},labels etc...
	Q string `protobuf:"bytes,5,opt,name=q,proto3" json:"q,omitempty"`
	// Sort result dataset of records by fields.
	// ```
	// sort ::= *( ORDER name )
	//
	// ORDER  = ASC / DESC
	// DESC   = "-" / "!"
	// ASC    = [ "+" ]   ; Default
	// ```
	//
	// # Fields available
	//
	// - `id`(seq)
	// - `domain`{name}
	// - `created_at`
	// - `created_by`{name}
	// - `updated_at`
	// - `updated_by`{name}
	//
	// Use ?fields=`field.sort()` option to sort Edge fields.
	Sort []string `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`
	// Fields [Q]uery to build result dataset record.
	// ```
	// fields ::= field [ *( "," field ) ]
	// field  ::= name [ *( func ) ] [ inner ]
	// inner  ::= "{" fields "}"
	// funcs  ::= *( func )
	// func   ::= "." name "(" [ args ] ")"
	// name   ::= ALPHA / DIGIT / USCORE
	//
	// ALPHA    = %x41-5A / %x61-7A  ; "A"-"Z" / "a"-"z"
	// DIGIT    = %x30-39            ; "0"-"9"
	// USCORE   = %x5F ; underscore  ; "_"
	// ```
	Fields []string `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	// Records with unique IDentifier(s).
	// Accept: `id` -or- `etag`.
	Id []string `protobuf:"bytes,6,rep,name=id,proto3" json:"id,omitempty"`
	// [Q]uery[IN] is a set of search fields for term `q`.
	// Default: `name{common_name}`.
	Qin []string `protobuf:"bytes,7,rep,name=qin,proto3" json:"qin,omitempty"`
	// Source access mode requirement.
	Mode AccessMode `protobuf:"varint,8,opt,name=mode,proto3,enum=webitel.contacts.AccessMode" json:"mode,omitempty"`
	// Excludes contacts that belong to the specified group ID.
	// - Filters out contacts associated with the given `group_id`.
	NotIdGroup int64 `protobuf:"varint,30,opt,name=not_id_group,json=notIdGroup,proto3" json:"not_id_group,omitempty"`
	// Filters contacts by the specified group(s).
	// - Includes only contacts that belong to one or more of the given group Group(s).
	Group []int64 `protobuf:"varint,31,rep,packed,name=group,proto3" json:"group,omitempty"`
	// Filters contacts by the specified owner(s).
	// - Includes only contacts whose owner matches one or more of the given Owner(s).
	// - The owner ID corresponds to `contact_id` in the `directory.wbt_user` table.
	Owner []int64 `protobuf:"varint,32,rep,packed,name=owner,proto3" json:"owner,omitempty"`
	// Filters contacts by the specified label(s).
	// - Includes only contacts that have one or more of the given Label(s).
	Label []string `protobuf:"bytes,33,rep,name=label,proto3" json:"label,omitempty"`
	// Filters contacts based on whether they are user-associated.
	// - `true`  → Includes only user-associated contacts.
	// - `false` → Includes only contacts that are NOT user-associated.
	// - A contact is considered user-associated if it exists in `directory.wbt_user`.
	User          *wrapperspb.BoolValue `protobuf:"bytes,34,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchContactsRequest) Reset() {
	*x = SearchContactsRequest{}
	mi := &file_contacts_contacts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchContactsRequest) ProtoMessage() {}

func (x *SearchContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contacts_contacts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchContactsRequest.ProtoReflect.Descriptor instead.
func (*SearchContactsRequest) Descriptor() ([]byte, []int) {
	return file_contacts_contacts_proto_rawDescGZIP(), []int{2}
}

func (x *SearchContactsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchContactsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchContactsRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchContactsRequest) GetSort() []string {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *SearchContactsRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SearchContactsRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SearchContactsRequest) GetQin() []string {
	if x != nil {
		return x.Qin
	}
	return nil
}

func (x *SearchContactsRequest) GetMode() AccessMode {
	if x != nil {
		return x.Mode
	}
	return AccessMode_READ
}

func (x *SearchContactsRequest) GetNotIdGroup() int64 {
	if x != nil {
		return x.NotIdGroup
	}
	return 0
}

func (x *SearchContactsRequest) GetGroup() []int64 {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *SearchContactsRequest) GetOwner() []int64 {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *SearchContactsRequest) GetLabel() []string {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *SearchContactsRequest) GetUser() *wrapperspb.BoolValue {
	if x != nil {
		return x.User
	}
	return nil
}

type SearchContactsNARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Q             string                 `protobuf:"bytes,5,opt,name=q,proto3" json:"q,omitempty"`
	Sort          []string               `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`
	Fields        []string               `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	Id            []string               `protobuf:"bytes,6,rep,name=id,proto3" json:"id,omitempty"`
	Qin           []string               `protobuf:"bytes,7,rep,name=qin,proto3" json:"qin,omitempty"`
	Mode          AccessMode             `protobuf:"varint,8,opt,name=mode,proto3,enum=webitel.contacts.AccessMode" json:"mode,omitempty"`
	DomainId      int64                  `protobuf:"varint,9,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchContactsNARequest) Reset() {
	*x = SearchContactsNARequest{}
	mi := &file_contacts_contacts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchContactsNARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchContactsNARequest) ProtoMessage() {}

func (x *SearchContactsNARequest) ProtoReflect() protoreflect.Message {
	mi := &file_contacts_contacts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchContactsNARequest.ProtoReflect.Descriptor instead.
func (*SearchContactsNARequest) Descriptor() ([]byte, []int) {
	return file_contacts_contacts_proto_rawDescGZIP(), []int{3}
}

func (x *SearchContactsNARequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchContactsNARequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchContactsNARequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchContactsNARequest) GetSort() []string {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *SearchContactsNARequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SearchContactsNARequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SearchContactsNARequest) GetQin() []string {
	if x != nil {
		return x.Qin
	}
	return nil
}

func (x *SearchContactsNARequest) GetMode() AccessMode {
	if x != nil {
		return x.Mode
	}
	return AccessMode_READ
}

func (x *SearchContactsNARequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

type InputContactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON PATCH fields mask.
	// List of JPath fields specified in body(input).
	XJsonMask []string `protobuf:"bytes,1,rep,name=x_json_mask,json=xJsonMask,proto3" json:"x_json_mask,omitempty"`
	// Source Fields to return into result.
	Fields []string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	// NEW Contact source changes
	Input         *InputContact `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContactRequest) Reset() {
	*x = InputContactRequest{}
	mi := &file_contacts_contacts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContactRequest) ProtoMessage() {}

func (x *InputContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contacts_contacts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContactRequest.ProtoReflect.Descriptor instead.
func (*InputContactRequest) Descriptor() ([]byte, []int) {
	return file_contacts_contacts_proto_rawDescGZIP(), []int{4}
}

func (x *InputContactRequest) GetXJsonMask() []string {
	if x != nil {
		return x.XJsonMask
	}
	return nil
}

func (x *InputContactRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *InputContactRequest) GetInput() *InputContact {
	if x != nil {
		return x.Input
	}
	return nil
}

type InputContactsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON PATCH fields mask.
	// List of JPath fields specified in body(input).
	XJsonMask []string `protobuf:"bytes,1,rep,name=x_json_mask,json=xJsonMask,proto3" json:"x_json_mask,omitempty"`
	// Source Fields to return into result.
	Fields []string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	// NEW Contacts source changes
	Input         []*InputContact `protobuf:"bytes,3,rep,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContactsRequest) Reset() {
	*x = InputContactsRequest{}
	mi := &file_contacts_contacts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContactsRequest) ProtoMessage() {}

func (x *InputContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contacts_contacts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContactsRequest.ProtoReflect.Descriptor instead.
func (*InputContactsRequest) Descriptor() ([]byte, []int) {
	return file_contacts_contacts_proto_rawDescGZIP(), []int{5}
}

func (x *InputContactsRequest) GetXJsonMask() []string {
	if x != nil {
		return x.XJsonMask
	}
	return nil
}

func (x *InputContactsRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *InputContactsRequest) GetInput() []*InputContact {
	if x != nil {
		return x.Input
	}
	return nil
}

type CreateContactsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fields to be retrieved into result of changes.
	Fields []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	// Data is a set of Contacts to be created.
	Input         []*InputContact `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContactsRequest) Reset() {
	*x = CreateContactsRequest{}
	mi := &file_contacts_contacts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContactsRequest) ProtoMessage() {}

func (x *CreateContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contacts_contacts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContactsRequest.ProtoReflect.Descriptor instead.
func (*CreateContactsRequest) Descriptor() ([]byte, []int) {
	return file_contacts_contacts_proto_rawDescGZIP(), []int{6}
}

func (x *CreateContactsRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *CreateContactsRequest) GetInput() []*InputContact {
	if x != nil {
		return x.Input
	}
	return nil
}

type DeleteContactsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fields to be retrieved into result of changes.
	Fields []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	// Set of unique Contact IDs to deal with
	Etag          []string `protobuf:"bytes,2,rep,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContactsRequest) Reset() {
	*x = DeleteContactsRequest{}
	mi := &file_contacts_contacts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContactsRequest) ProtoMessage() {}

func (x *DeleteContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contacts_contacts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContactsRequest.ProtoReflect.Descriptor instead.
func (*DeleteContactsRequest) Descriptor() ([]byte, []int) {
	return file_contacts_contacts_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteContactsRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DeleteContactsRequest) GetEtag() []string {
	if x != nil {
		return x.Etag
	}
	return nil
}

type DeleteContactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fields to be retrieved into result of changes.
	Fields []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	// Unique ID of the latest version of a resource.
	Etag          string `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContactRequest) Reset() {
	*x = DeleteContactRequest{}
	mi := &file_contacts_contacts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContactRequest) ProtoMessage() {}

func (x *DeleteContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contacts_contacts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContactRequest.ProtoReflect.Descriptor instead.
func (*DeleteContactRequest) Descriptor() ([]byte, []int) {
	return file_contacts_contacts_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteContactRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DeleteContactRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

var File_contacts_contacts_proto protoreflect.FileDescriptor

const file_contacts_contacts_proto_rawDesc = "" +
	"\n" +
	"\x17contacts/contacts.proto\x12\x10webitel.contacts\x1a\x15contacts/fields.proto\x1a\x16contacts/contact.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/api/visibility.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"d\n" +
	"\vContactList\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.webitel.contacts.ContactR\x04data\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04next\x18\x03 \x01(\bR\x04next\"t\n" +
	"\x14LocateContactRequest\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\x120\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x1c.webitel.contacts.AccessModeR\x04mode\"\xd7\x03\n" +
	"\x15SearchContactsRequest\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\x12\f\n" +
	"\x01q\x18\x05 \x01(\tR\x01q\x12E\n" +
	"\x04sort\x18\x03 \x03(\tB1\x92A.:\x02idJ\x11\"!updated_at,tag\"\x8a\x01\r^[+|-|!]?\\w+$\xb0\x01\x01\x9a\x02\x01\x01R\x04sort\x12Y\n" +
	"\x06fields\x18\x04 \x03(\tBA\x92A>:\x01*J6\"*,labels.size(3).sort(!updated_at){updated_at,label}\"\xb0\x01\x01R\x06fields\x12\x0e\n" +
	"\x02id\x18\x06 \x03(\tR\x02id\x12\x10\n" +
	"\x03qin\x18\a \x03(\tR\x03qin\x120\n" +
	"\x04mode\x18\b \x01(\x0e2\x1c.webitel.contacts.AccessModeR\x04mode\x12 \n" +
	"\fnot_id_group\x18\x1e \x01(\x03R\n" +
	"notIdGroup\x12\x14\n" +
	"\x05group\x18\x1f \x03(\x03R\x05group\x12\x14\n" +
	"\x05owner\x18  \x03(\x03R\x05owner\x12\x14\n" +
	"\x05label\x18! \x03(\tR\x05label\x12.\n" +
	"\x04user\x18\" \x01(\v2\x1a.google.protobuf.BoolValueR\x04user\"\xec\x01\n" +
	"\x17SearchContactsNARequest\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\x12\f\n" +
	"\x01q\x18\x05 \x01(\tR\x01q\x12\x12\n" +
	"\x04sort\x18\x03 \x03(\tR\x04sort\x12\x16\n" +
	"\x06fields\x18\x04 \x03(\tR\x06fields\x12\x0e\n" +
	"\x02id\x18\x06 \x03(\tR\x02id\x12\x10\n" +
	"\x03qin\x18\a \x03(\tR\x03qin\x120\n" +
	"\x04mode\x18\b \x01(\x0e2\x1c.webitel.contacts.AccessModeR\x04mode\x12\x1b\n" +
	"\tdomain_id\x18\t \x01(\x03R\bdomainId\"\x9e\x01\n" +
	"\x13InputContactRequest\x129\n" +
	"\vx_json_mask\x18\x01 \x03(\tB\x19\x92A\a@\x01\x8a\x01\x02^$\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEWR\txJsonMask\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\x124\n" +
	"\x05input\x18\x03 \x01(\v2\x1e.webitel.contacts.InputContactR\x05input\"\xa0\x01\n" +
	"\x14InputContactsRequest\x12:\n" +
	"\vx_json_mask\x18\x01 \x03(\tB\x1a\x92A\a@\x01\x8a\x01\x02^$\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNALR\txJsonMask\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\x124\n" +
	"\x05input\x18\x03 \x03(\v2\x1e.webitel.contacts.InputContactR\x05input\"p\n" +
	"\x15CreateContactsRequest\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\x12?\n" +
	"\x05input\x18\x02 \x03(\v2\x1e.webitel.contacts.InputContactB\t\x92A\x06\xa8\x01\x01\xb0\x01\x01R\x05input\"n\n" +
	"\x15DeleteContactsRequest\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\x12/\n" +
	"\x04etag\x18\x02 \x03(\tB\x1b\x92A\x18\x8a\x01\x05^\\w+$\xa8\x01\x01\xb0\x01\x01\xca>\a\xfa\x02\x04etagR\x04etag:\f\x92A\t\n" +
	"\a\xd2\x01\x04etag\"g\n" +
	"\x14DeleteContactRequest\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\x12)\n" +
	"\x04etag\x18\x02 \x01(\tB\x15\x92A\x12\x8a\x01\x05^\\w+$\xca>\a\xfa\x02\x04etagR\x04etag:\f\x92A\t\n" +
	"\a\xd2\x01\x04etag2\xa9\v\n" +
	"\bContacts\x12\xf9\x06\n" +
	"\x0eSearchContacts\x12'.webitel.contacts.SearchContactsRequest\x1a\x1d.webitel.contacts.ContactList\"\x9e\x06\x92A\x89\x06\x1a\x86\x06| Field       | Type \n" +
	"| ----------- | ---- \n" +
	"| **----------- READ-ONLY -----------** | \n" +
	"| `id`        | int64 \n" +
	"| `ver`       | int32 \n" +
	"| `etag`      | string \n" +
	"| **---------- OPERATIONAL ----------** | \n" +
	"| `created_at` | int64(epoch:milli) \n" +
	"| `created_by` | lookup(user) \n" +
	"| `updated_at` | int64(epoch:milli) \n" +
	"| `updated_by` | lookup(user) \n" +
	"| **---------- ATTRIBUTES -----------** | \n" +
	"| `name`      | name! \n" +
	"| `about`     | string \n" +
	"| `labels`    | list[label!] \n" +
	"| `emails`    | list[email!] \n" +
	"| `photos`    | list[photo!] \n" +
	"| `phones`    | list[phone!] \n" +
	"| `managers`  | list[manager!] \n" +
	"| `comments`  | list[comment!] \n" +
	"| `addresses` | list[address!] \n" +
	"| `languages` | list[language!] \n" +
	"| `timezones` | list[timezone!] \n" +
	"| `variables` | list[variable!] \n" +
	"| `imclients` | list[imClient!] \n" +
	"\x82\xd3\xe4\x93\x02\v\x12\t/contacts\x12^\n" +
	"\x10SearchContactsNA\x12).webitel.contacts.SearchContactsNARequest\x1a\x1d.webitel.contacts.ContactList\"\x00\x12l\n" +
	"\rLocateContact\x12&.webitel.contacts.LocateContactRequest\x1a\x19.webitel.contacts.Contact\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/contacts/{etag}\x12k\n" +
	"\rCreateContact\x12%.webitel.contacts.InputContactRequest\x1a\x19.webitel.contacts.Contact\"\x18\x82\xd3\xe4\x93\x02\x12:\x05input\"\t/contacts\x12x\n" +
	"\rUpdateContact\x12%.webitel.contacts.InputContactRequest\x1a\x19.webitel.contacts.Contact\"%\x82\xd3\xe4\x93\x02\x1f:\x05input2\x16/contacts/{input.etag}\x12l\n" +
	"\rDeleteContact\x12&.webitel.contacts.DeleteContactRequest\x1a\x19.webitel.contacts.Contact\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/contacts/{etag}B\xa8\x01\n" +
	"\x14com.webitel.contactsB\rContactsProtoP\x01Z webitel.go/api/contacts;contacts\xa2\x02\x03WCX\xaa\x02\x10Webitel.Contacts\xca\x02\x10Webitel\\Contacts\xe2\x02\x1cWebitel\\Contacts\\GPBMetadata\xea\x02\x11Webitel::Contactsb\x06proto3"

var (
	file_contacts_contacts_proto_rawDescOnce sync.Once
	file_contacts_contacts_proto_rawDescData []byte
)

func file_contacts_contacts_proto_rawDescGZIP() []byte {
	file_contacts_contacts_proto_rawDescOnce.Do(func() {
		file_contacts_contacts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contacts_contacts_proto_rawDesc), len(file_contacts_contacts_proto_rawDesc)))
	})
	return file_contacts_contacts_proto_rawDescData
}

var file_contacts_contacts_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_contacts_contacts_proto_goTypes = []any{
	(*ContactList)(nil),             // 0: webitel.contacts.ContactList
	(*LocateContactRequest)(nil),    // 1: webitel.contacts.LocateContactRequest
	(*SearchContactsRequest)(nil),   // 2: webitel.contacts.SearchContactsRequest
	(*SearchContactsNARequest)(nil), // 3: webitel.contacts.SearchContactsNARequest
	(*InputContactRequest)(nil),     // 4: webitel.contacts.InputContactRequest
	(*InputContactsRequest)(nil),    // 5: webitel.contacts.InputContactsRequest
	(*CreateContactsRequest)(nil),   // 6: webitel.contacts.CreateContactsRequest
	(*DeleteContactsRequest)(nil),   // 7: webitel.contacts.DeleteContactsRequest
	(*DeleteContactRequest)(nil),    // 8: webitel.contacts.DeleteContactRequest
	(*Contact)(nil),                 // 9: webitel.contacts.Contact
	(AccessMode)(0),                 // 10: webitel.contacts.AccessMode
	(*wrapperspb.BoolValue)(nil),    // 11: google.protobuf.BoolValue
	(*InputContact)(nil),            // 12: webitel.contacts.InputContact
}
var file_contacts_contacts_proto_depIdxs = []int32{
	9,  // 0: webitel.contacts.ContactList.data:type_name -> webitel.contacts.Contact
	10, // 1: webitel.contacts.LocateContactRequest.mode:type_name -> webitel.contacts.AccessMode
	10, // 2: webitel.contacts.SearchContactsRequest.mode:type_name -> webitel.contacts.AccessMode
	11, // 3: webitel.contacts.SearchContactsRequest.user:type_name -> google.protobuf.BoolValue
	10, // 4: webitel.contacts.SearchContactsNARequest.mode:type_name -> webitel.contacts.AccessMode
	12, // 5: webitel.contacts.InputContactRequest.input:type_name -> webitel.contacts.InputContact
	12, // 6: webitel.contacts.InputContactsRequest.input:type_name -> webitel.contacts.InputContact
	12, // 7: webitel.contacts.CreateContactsRequest.input:type_name -> webitel.contacts.InputContact
	2,  // 8: webitel.contacts.Contacts.SearchContacts:input_type -> webitel.contacts.SearchContactsRequest
	3,  // 9: webitel.contacts.Contacts.SearchContactsNA:input_type -> webitel.contacts.SearchContactsNARequest
	1,  // 10: webitel.contacts.Contacts.LocateContact:input_type -> webitel.contacts.LocateContactRequest
	4,  // 11: webitel.contacts.Contacts.CreateContact:input_type -> webitel.contacts.InputContactRequest
	4,  // 12: webitel.contacts.Contacts.UpdateContact:input_type -> webitel.contacts.InputContactRequest
	8,  // 13: webitel.contacts.Contacts.DeleteContact:input_type -> webitel.contacts.DeleteContactRequest
	0,  // 14: webitel.contacts.Contacts.SearchContacts:output_type -> webitel.contacts.ContactList
	0,  // 15: webitel.contacts.Contacts.SearchContactsNA:output_type -> webitel.contacts.ContactList
	9,  // 16: webitel.contacts.Contacts.LocateContact:output_type -> webitel.contacts.Contact
	9,  // 17: webitel.contacts.Contacts.CreateContact:output_type -> webitel.contacts.Contact
	9,  // 18: webitel.contacts.Contacts.UpdateContact:output_type -> webitel.contacts.Contact
	9,  // 19: webitel.contacts.Contacts.DeleteContact:output_type -> webitel.contacts.Contact
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_contacts_contacts_proto_init() }
func file_contacts_contacts_proto_init() {
	if File_contacts_contacts_proto != nil {
		return
	}
	file_contacts_fields_proto_init()
	file_contacts_contact_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contacts_contacts_proto_rawDesc), len(file_contacts_contacts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contacts_contacts_proto_goTypes,
		DependencyIndexes: file_contacts_contacts_proto_depIdxs,
		MessageInfos:      file_contacts_contacts_proto_msgTypes,
	}.Build()
	File_contacts_contacts_proto = out.File
	file_contacts_contacts_proto_goTypes = nil
	file_contacts_contacts_proto_depIdxs = nil
}
