name: Development

on:
  push:
    branches:
      - main

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/go-prepare.yml@main
    with:
      development-branch: main
      triggered-branch: ${{ github.ref_name }}
      build-number: ${{ github.run_number }}

  compile:
    name: Build
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/go-build.yml@main
    with:
      version: ${{ needs.prepare.outputs.version }}
      source: ${{ vars.PACKAGE_PATTERN }}

  deploy:
    name: Deploy
    needs: [ prepare, compile ]
    uses: webitel/reusable-workflows/.github/workflows/_deploy.yml@main
    secrets: inherit
    with:
      component: ${{ needs.prepare.outputs.component }}
      repository-environment: acceptance