name: PR

on:
  pull_request:

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/go-prepare.yml@main
    with:
      only-dependencies: true
      generate-code: ${{ vars.USE_GENERATED_CODE }}
      wire: ${{ vars.USE_GENERATED_CODE_WIRE }}

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/go-checks.yml@main
    with:
      generated-code: ${{ vars.USE_GENERATED_CODE }}
      wire: ${{ vars.USE_GENERATED_CODE_WIRE }}